<div style="font-variant: small-caps; 
      font-weight: normal; 
      font-size: 37px; 
      text-align: center; 
      padding: 15px; 
      margin: 10px;">
  Machine Learning in credit scoring <br>
  </div> 

<div style="font-variant: small-caps; 
      font-weight: normal; 
      font-size: 25px; 
      text-align: center; 
      padding: 15px; 
      margin: 10px;">
      <font color=orange> Classification</font>
  </div>

<div style="font-variant: small-caps; 
      font-weight: normal; 
      font-size: 20px; 
      text-align: center; 
      padding: 15px; 
      margin: 10px;">
      Arystan, Sirine, Jules and Augustin
      
  </div>

# 1. Imporiting Libraries

In [ ]:
%load_ext autoreload
%autoreload 2

%matplotlib inline

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from pathlib import Path
import joblib

from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, precision_score, recall_score, f1_score
from sklearn.ensemble import RandomForestClassifier


from imblearn.over_sampling import SMOTE
from catboost import CatBoostClassifier, Pool
from lightgbm import LGBMClassifier
from xgboost import XGBClassifier

import optuna

pd.set_option("display.max_columns", None)

/opt/miniconda3/envs/arystan_credit/lib/python3.13/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

# 2. Data Loading

In [2]:
path_to_repo = Path('..').resolve()
path_to_data = path_to_repo / 'data'

In [3]:
df = pd.read_csv(path_to_data / 'preprocessed_data.csv')

In [4]:
y = df["bad"]
X = df.drop(columns=["bad", "ID"])

In [5]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

# RANDOM FOREST CLASSIFIER

In [6]:
rf_base = RandomForestClassifier(random_state=42)
%time rf_base.fit(X_train, y_train)

CPU times: user 969 ms, sys: 13.3 ms, total: 983 ms
Wall time: 992 ms

RandomForestClassifier(random_state=42)

In [7]:
y_pred_default = rf_base.predict(X_test)

In [8]:
print(classification_report(y_test, y_pred_default))

              precision    recall  f1-score   support

           0       0.99      1.00      0.99      7169
           1       0.33      0.14      0.19       123

    accuracy                           0.98      7292
   macro avg       0.66      0.57      0.59      7292
weighted avg       0.97      0.98      0.98      7292

In [9]:
rf_default_balanced = RandomForestClassifier(random_state=42, class_weight='balanced')
%time rf_default_balanced.fit(X_train, y_train)

CPU times: user 997 ms, sys: 12.1 ms, total: 1.01 s
Wall time: 1.01 s

RandomForestClassifier(class_weight='balanced', random_state=42)

In [10]:
y_pred_default_balanced = rf_default_balanced.predict(X_test)
print(classification_report(y_test, y_pred_default))

              precision    recall  f1-score   support

           0       0.99      1.00      0.99      7169
           1       0.33      0.14      0.19       123

    accuracy                           0.98      7292
   macro avg       0.66      0.57      0.59      7292
weighted avg       0.97      0.98      0.98      7292

In [11]:
feature_importance = pd.DataFrame({'feature': X.columns,'importance': rf_default_balanced.feature_importances_}).sort_values('importance', ascending=False)
feature_importance.head(20)

                feature  importance
13                  AGE    0.220440
15           LOG_INCOME    0.208378
14           EXPERIENCE    0.142290
6    NAME_FAMILY_STATUS    0.050596
4      NAME_INCOME_TYPE    0.050519
12      CNT_FAM_MEMBERS    0.048632
5   NAME_EDUCATION_TYPE    0.044144
1          FLAG_OWN_CAR    0.035269
3          CNT_CHILDREN    0.034801
10           FLAG_PHONE    0.034329
2       FLAG_OWN_REALTY    0.031249
7     NAME_HOUSING_TYPE    0.028651
0           CODE_GENDER    0.026966
9       FLAG_WORK_PHONE    0.025263
11           FLAG_EMAIL    0.018473
8            FLAG_MOBIL    0.000000

In [12]:
rf_default_balanced_subsample = RandomForestClassifier(random_state=42,
                                    class_weight='balanced_subsample')
%time rf_default_balanced_subsample.fit(X_train, y_train)

CPU times: user 1.3 s, sys: 38.8 ms, total: 1.34 s
Wall time: 1.48 s

RandomForestClassifier(class_weight='balanced_subsample', random_state=42)

In [13]:
y_pred_default_balanced_subsample = rf_default_balanced_subsample.predict(X_test)
print(classification_report(y_test, y_pred_default))

              precision    recall  f1-score   support

           0       0.99      1.00      0.99      7169
           1       0.33      0.14      0.19       123

    accuracy                           0.98      7292
   macro avg       0.66      0.57      0.59      7292
weighted avg       0.97      0.98      0.98      7292

## RF + Hyperparameter Tuning

In [14]:
def objective_rf(trial, X_train, y_train, X_val, y_val):

    n_estimators = trial.suggest_int("n_estimators", 50, 300)
    max_depth = trial.suggest_int("max_depth", 5, 30)
    min_samples_split = trial.suggest_int("min_samples_split", 2, 15)
    min_samples_leaf = trial.suggest_int("min_samples_leaf", 1, 10)
    class_weight = trial.suggest_categorical("class_weight",
                                             ["balanced", "balanced_subsample"])

    model = RandomForestClassifier(
        n_estimators=n_estimators,
        max_depth=max_depth,
        min_samples_split=min_samples_split,
        min_samples_leaf=min_samples_leaf,
        class_weight=class_weight,
        random_state=42,
        n_jobs=-1
    )

    model.fit(X_train, y_train)

    y_pred = model.predict(X_val)
    f1 = f1_score(y_val, y_pred)

    return f1

In [15]:
X_train, X_temp, y_train, y_temp = train_test_split(
    X, y, test_size=0.30, random_state=42, stratify=y
)

X_val, X_test, y_val, y_test = train_test_split(
    X_temp, y_temp, test_size=0.50, random_state=42, stratify=y_temp
)

In [ ]:
study_rf = optuna.create_study(
    study_name="rf_opt",
    direction="maximize",
    storage="sqlite:///.../models/rf_opt.db",
    load_if_exists=True
)

study_rf.optimize(lambda trial: objective_rf(trial, X_train, y_train, X_val, y_val),n_trials=50, show_progress_bar=True)

[I 2025-12-07 15:19:33,295] A new study created in RDB with name: rf_opt
Best trial: 0. Best value: 0.253275:   2%|▏         | 1/50 [00:00<00:25,  1.92it/s]

[I 2025-12-07 15:19:33,819] Trial 0 finished with value: 0.25327510917030566 and parameters: {'n_estimators': 203, 'max_depth': 15, 'min_samples_split': 8, 'min_samples_leaf': 3, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.25327510917030566.

Best trial: 1. Best value: 0.260163:   4%|▍         | 2/50 [00:01<00:36,  1.31it/s]

[I 2025-12-07 15:19:34,749] Trial 1 finished with value: 0.2601626016260163 and parameters: {'n_estimators': 247, 'max_depth': 25, 'min_samples_split': 14, 'min_samples_leaf': 5, 'class_weight': 'balanced_subsample'}. Best is trial 1 with value: 0.2601626016260163.

Best trial: 1. Best value: 0.260163:   6%|▌         | 3/50 [00:01<00:28,  1.64it/s]

[I 2025-12-07 15:19:35,180] Trial 2 finished with value: 0.23107569721115537 and parameters: {'n_estimators': 163, 'max_depth': 14, 'min_samples_split': 7, 'min_samples_leaf': 6, 'class_weight': 'balanced'}. Best is trial 1 with value: 0.2601626016260163.

Best trial: 1. Best value: 0.260163:   8%|▊         | 4/50 [00:02<00:33,  1.39it/s]

[I 2025-12-07 15:19:36,076] Trial 3 finished with value: 0.24390243902439024 and parameters: {'n_estimators': 258, 'max_depth': 15, 'min_samples_split': 14, 'min_samples_leaf': 5, 'class_weight': 'balanced_subsample'}. Best is trial 1 with value: 0.2601626016260163.

Best trial: 1. Best value: 0.260163:  10%|█         | 5/50 [00:03<00:26,  1.68it/s]

[I 2025-12-07 15:19:36,445] Trial 4 finished with value: 0.25316455696202533 and parameters: {'n_estimators': 164, 'max_depth': 15, 'min_samples_split': 13, 'min_samples_leaf': 4, 'class_weight': 'balanced'}. Best is trial 1 with value: 0.2601626016260163.

Best trial: 1. Best value: 0.260163:  12%|█▏        | 6/50 [00:03<00:21,  2.02it/s]

[I 2025-12-07 15:19:36,748] Trial 5 finished with value: 0.25396825396825395 and parameters: {'n_estimators': 82, 'max_depth': 25, 'min_samples_split': 12, 'min_samples_leaf': 8, 'class_weight': 'balanced_subsample'}. Best is trial 1 with value: 0.2601626016260163.

Best trial: 1. Best value: 0.260163:  14%|█▍        | 7/50 [00:04<00:26,  1.64it/s]

[I 2025-12-07 15:19:37,591] Trial 6 finished with value: 0.24096385542168675 and parameters: {'n_estimators': 256, 'max_depth': 16, 'min_samples_split': 7, 'min_samples_leaf': 7, 'class_weight': 'balanced_subsample'}. Best is trial 1 with value: 0.2601626016260163.

Best trial: 1. Best value: 0.260163:  16%|█▌        | 8/50 [00:05<00:28,  1.45it/s]

[I 2025-12-07 15:19:38,450] Trial 7 finished with value: 0.24390243902439024 and parameters: {'n_estimators': 252, 'max_depth': 23, 'min_samples_split': 4, 'min_samples_leaf': 2, 'class_weight': 'balanced_subsample'}. Best is trial 1 with value: 0.2601626016260163.

Best trial: 1. Best value: 0.260163:  18%|█▊        | 9/50 [00:05<00:25,  1.61it/s]

[I 2025-12-07 15:19:38,927] Trial 8 finished with value: 0.242914979757085 and parameters: {'n_estimators': 225, 'max_depth': 30, 'min_samples_split': 15, 'min_samples_leaf': 2, 'class_weight': 'balanced'}. Best is trial 1 with value: 0.2601626016260163.

Best trial: 1. Best value: 0.260163:  20%|██        | 10/50 [00:06<00:22,  1.78it/s]

[I 2025-12-07 15:19:39,356] Trial 9 finished with value: 0.25316455696202533 and parameters: {'n_estimators': 118, 'max_depth': 21, 'min_samples_split': 4, 'min_samples_leaf': 6, 'class_weight': 'balanced_subsample'}. Best is trial 1 with value: 0.2601626016260163.

Best trial: 1. Best value: 0.260163:  22%|██▏       | 11/50 [00:08<00:48,  1.23s/it]

[I 2025-12-07 15:19:42,102] Trial 10 finished with value: 0.08025682182985554 and parameters: {'n_estimators': 285, 'max_depth': 7, 'min_samples_split': 11, 'min_samples_leaf': 10, 'class_weight': 'balanced_subsample'}. Best is trial 1 with value: 0.2601626016260163.

Best trial: 1. Best value: 0.260163:  24%|██▍       | 12/50 [00:09<00:38,  1.02s/it]

[I 2025-12-07 15:19:42,641] Trial 11 finished with value: 0.24313725490196078 and parameters: {'n_estimators': 70, 'max_depth': 28, 'min_samples_split': 11, 'min_samples_leaf': 9, 'class_weight': 'balanced_subsample'}. Best is trial 1 with value: 0.2601626016260163.

Best trial: 1. Best value: 0.260163:  26%|██▌       | 13/50 [00:09<00:32,  1.14it/s]

[I 2025-12-07 15:19:43,177] Trial 12 finished with value: 0.2421875 and parameters: {'n_estimators': 61, 'max_depth': 25, 'min_samples_split': 11, 'min_samples_leaf': 8, 'class_weight': 'balanced_subsample'}. Best is trial 1 with value: 0.2601626016260163.

Best trial: 1. Best value: 0.260163:  28%|██▊       | 14/50 [00:10<00:30,  1.20it/s]

[I 2025-12-07 15:19:43,924] Trial 13 finished with value: 0.25396825396825395 and parameters: {'n_estimators': 108, 'max_depth': 27, 'min_samples_split': 13, 'min_samples_leaf': 8, 'class_weight': 'balanced_subsample'}. Best is trial 1 with value: 0.2601626016260163.

Best trial: 1. Best value: 0.260163:  30%|███       | 15/50 [00:12<00:43,  1.23s/it]

[I 2025-12-07 15:19:46,027] Trial 14 finished with value: 0.24390243902439024 and parameters: {'n_estimators': 300, 'max_depth': 20, 'min_samples_split': 10, 'min_samples_leaf': 4, 'class_weight': 'balanced_subsample'}. Best is trial 1 with value: 0.2601626016260163.

Best trial: 1. Best value: 0.260163:  32%|███▏      | 16/50 [00:13<00:40,  1.19s/it]

[I 2025-12-07 15:19:47,164] Trial 15 finished with value: 0.23904382470119523 and parameters: {'n_estimators': 130, 'max_depth': 24, 'min_samples_split': 14, 'min_samples_leaf': 10, 'class_weight': 'balanced_subsample'}. Best is trial 1 with value: 0.2601626016260163.

Best trial: 1. Best value: 0.260163:  34%|███▍      | 17/50 [00:15<00:42,  1.29s/it]

[I 2025-12-07 15:19:48,685] Trial 16 finished with value: 0.2549800796812749 and parameters: {'n_estimators': 191, 'max_depth': 20, 'min_samples_split': 2, 'min_samples_leaf': 7, 'class_weight': 'balanced_subsample'}. Best is trial 1 with value: 0.2601626016260163.

Best trial: 1. Best value: 0.260163:  36%|███▌      | 18/50 [00:16<00:41,  1.28s/it]

[I 2025-12-07 15:19:49,954] Trial 17 finished with value: 0.1793103448275862 and parameters: {'n_estimators': 196, 'max_depth': 10, 'min_samples_split': 3, 'min_samples_leaf': 5, 'class_weight': 'balanced_subsample'}. Best is trial 1 with value: 0.2601626016260163.

Best trial: 1. Best value: 0.260163:  38%|███▊      | 19/50 [00:17<00:34,  1.10s/it]

[I 2025-12-07 15:19:50,630] Trial 18 finished with value: 0.2572614107883817 and parameters: {'n_estimators': 219, 'max_depth': 19, 'min_samples_split': 2, 'min_samples_leaf': 1, 'class_weight': 'balanced'}. Best is trial 1 with value: 0.2601626016260163.

Best trial: 1. Best value: 0.260163:  40%|████      | 20/50 [00:17<00:28,  1.06it/s]

[I 2025-12-07 15:19:51,213] Trial 19 finished with value: 0.184 and parameters: {'n_estimators': 227, 'max_depth': 11, 'min_samples_split': 6, 'min_samples_leaf': 1, 'class_weight': 'balanced'}. Best is trial 1 with value: 0.2601626016260163.

Best trial: 1. Best value: 0.260163:  42%|████▏     | 21/50 [00:18<00:23,  1.22it/s]

[I 2025-12-07 15:19:51,735] Trial 20 finished with value: 0.2594142259414226 and parameters: {'n_estimators': 226, 'max_depth': 18, 'min_samples_split': 9, 'min_samples_leaf': 1, 'class_weight': 'balanced'}. Best is trial 1 with value: 0.2601626016260163.

Best trial: 1. Best value: 0.260163:  44%|████▍     | 22/50 [00:18<00:20,  1.40it/s]

[I 2025-12-07 15:19:52,212] Trial 21 finished with value: 0.2594142259414226 and parameters: {'n_estimators': 225, 'max_depth': 18, 'min_samples_split': 9, 'min_samples_leaf': 1, 'class_weight': 'balanced'}. Best is trial 1 with value: 0.2601626016260163.

Best trial: 1. Best value: 0.260163:  46%|████▌     | 23/50 [00:19<00:17,  1.54it/s]

[I 2025-12-07 15:19:52,705] Trial 22 finished with value: 0.2551440329218107 and parameters: {'n_estimators': 240, 'max_depth': 18, 'min_samples_split': 9, 'min_samples_leaf': 2, 'class_weight': 'balanced'}. Best is trial 1 with value: 0.2601626016260163.

Best trial: 1. Best value: 0.260163:  48%|████▊     | 24/50 [00:19<00:16,  1.58it/s]

[I 2025-12-07 15:19:53,295] Trial 23 finished with value: 0.242914979757085 and parameters: {'n_estimators': 280, 'max_depth': 22, 'min_samples_split': 9, 'min_samples_leaf': 3, 'class_weight': 'balanced'}. Best is trial 1 with value: 0.2601626016260163.

Best trial: 1. Best value: 0.260163:  50%|█████     | 25/50 [00:20<00:13,  1.91it/s]

[I 2025-12-07 15:19:53,572] Trial 24 finished with value: 0.05378973105134474 and parameters: {'n_estimators': 175, 'max_depth': 5, 'min_samples_split': 6, 'min_samples_leaf': 1, 'class_weight': 'balanced'}. Best is trial 1 with value: 0.2601626016260163.

Best trial: 1. Best value: 0.260163:  52%|█████▏    | 26/50 [00:20<00:11,  2.04it/s]

[I 2025-12-07 15:19:53,985] Trial 25 finished with value: 0.22764227642276422 and parameters: {'n_estimators': 207, 'max_depth': 12, 'min_samples_split': 10, 'min_samples_leaf': 3, 'class_weight': 'balanced'}. Best is trial 1 with value: 0.2601626016260163.

Best trial: 1. Best value: 0.260163:  54%|█████▍    | 27/50 [00:21<00:11,  1.95it/s]

[I 2025-12-07 15:19:54,550] Trial 26 finished with value: 0.24793388429752067 and parameters: {'n_estimators': 274, 'max_depth': 17, 'min_samples_split': 8, 'min_samples_leaf': 4, 'class_weight': 'balanced'}. Best is trial 1 with value: 0.2601626016260163.

Best trial: 1. Best value: 0.260163:  56%|█████▌    | 28/50 [00:21<00:11,  1.97it/s]

[I 2025-12-07 15:19:55,046] Trial 27 finished with value: 0.2551440329218107 and parameters: {'n_estimators': 238, 'max_depth': 18, 'min_samples_split': 6, 'min_samples_leaf': 2, 'class_weight': 'balanced'}. Best is trial 1 with value: 0.2601626016260163.

Best trial: 1. Best value: 0.260163:  58%|█████▊    | 29/50 [00:22<00:09,  2.12it/s]

[I 2025-12-07 15:19:55,436] Trial 28 finished with value: 0.2510822510822511 and parameters: {'n_estimators': 180, 'max_depth': 13, 'min_samples_split': 15, 'min_samples_leaf': 1, 'class_weight': 'balanced'}. Best is trial 1 with value: 0.2601626016260163.

Best trial: 1. Best value: 0.260163:  60%|██████    | 30/50 [00:22<00:08,  2.42it/s]

[I 2025-12-07 15:19:55,713] Trial 29 finished with value: 0.1588235294117647 and parameters: {'n_estimators': 150, 'max_depth': 9, 'min_samples_split': 10, 'min_samples_leaf': 3, 'class_weight': 'balanced'}. Best is trial 1 with value: 0.2601626016260163.

Best trial: 1. Best value: 0.260163:  62%|██████▏   | 31/50 [00:23<00:12,  1.50it/s]

[I 2025-12-07 15:19:56,945] Trial 30 finished with value: 0.2570281124497992 and parameters: {'n_estimators': 207, 'max_depth': 28, 'min_samples_split': 12, 'min_samples_leaf': 2, 'class_weight': 'balanced'}. Best is trial 1 with value: 0.2601626016260163.

Best trial: 1. Best value: 0.260163:  64%|██████▍   | 32/50 [00:24<00:14,  1.23it/s]

[I 2025-12-07 15:19:58,111] Trial 31 finished with value: 0.25101214574898784 and parameters: {'n_estimators': 216, 'max_depth': 19, 'min_samples_split': 5, 'min_samples_leaf': 1, 'class_weight': 'balanced'}. Best is trial 1 with value: 0.2601626016260163.

Best trial: 1. Best value: 0.260163:  66%|██████▌   | 33/50 [00:25<00:15,  1.10it/s]

[I 2025-12-07 15:19:59,229] Trial 32 finished with value: 0.2594142259414226 and parameters: {'n_estimators': 236, 'max_depth': 17, 'min_samples_split': 7, 'min_samples_leaf': 1, 'class_weight': 'balanced'}. Best is trial 1 with value: 0.2601626016260163.

Best trial: 33. Best value: 0.262712:  68%|██████▊   | 34/50 [00:27<00:15,  1.03it/s]

[I 2025-12-07 15:20:00,346] Trial 33 finished with value: 0.2627118644067797 and parameters: {'n_estimators': 239, 'max_depth': 16, 'min_samples_split': 7, 'min_samples_leaf': 3, 'class_weight': 'balanced'}. Best is trial 33 with value: 0.2627118644067797.

Best trial: 33. Best value: 0.262712:  70%|███████   | 35/50 [00:28<00:15,  1.02s/it]

[I 2025-12-07 15:20:01,496] Trial 34 finished with value: 0.23628691983122363 and parameters: {'n_estimators': 256, 'max_depth': 14, 'min_samples_split': 8, 'min_samples_leaf': 5, 'class_weight': 'balanced'}. Best is trial 33 with value: 0.2627118644067797.

Best trial: 33. Best value: 0.262712:  72%|███████▏  | 36/50 [00:29<00:13,  1.02it/s]

[I 2025-12-07 15:20:02,389] Trial 35 finished with value: 0.25 and parameters: {'n_estimators': 266, 'max_depth': 15, 'min_samples_split': 8, 'min_samples_leaf': 4, 'class_weight': 'balanced'}. Best is trial 33 with value: 0.2627118644067797.

Best trial: 33. Best value: 0.262712:  74%|███████▍  | 37/50 [00:30<00:13,  1.03s/it]

[I 2025-12-07 15:20:03,542] Trial 36 finished with value: 0.24193548387096775 and parameters: {'n_estimators': 246, 'max_depth': 22, 'min_samples_split': 9, 'min_samples_leaf': 3, 'class_weight': 'balanced'}. Best is trial 33 with value: 0.2627118644067797.

Best trial: 33. Best value: 0.262712:  76%|███████▌  | 38/50 [00:31<00:14,  1.18s/it]

[I 2025-12-07 15:20:05,058] Trial 37 finished with value: 0.25833333333333336 and parameters: {'n_estimators': 300, 'max_depth': 16, 'min_samples_split': 7, 'min_samples_leaf': 3, 'class_weight': 'balanced'}. Best is trial 33 with value: 0.2627118644067797.

Best trial: 33. Best value: 0.262712:  78%|███████▊  | 39/50 [00:33<00:13,  1.24s/it]

[I 2025-12-07 15:20:06,442] Trial 38 finished with value: 0.23529411764705882 and parameters: {'n_estimators': 271, 'max_depth': 13, 'min_samples_split': 13, 'min_samples_leaf': 6, 'class_weight': 'balanced'}. Best is trial 33 with value: 0.2627118644067797.

Best trial: 33. Best value: 0.262712:  80%|████████  | 40/50 [00:33<00:10,  1.10s/it]

[I 2025-12-07 15:20:07,209] Trial 39 finished with value: 0.2601626016260163 and parameters: {'n_estimators': 186, 'max_depth': 23, 'min_samples_split': 5, 'min_samples_leaf': 2, 'class_weight': 'balanced'}. Best is trial 33 with value: 0.2627118644067797.

Best trial: 33. Best value: 0.262712:  82%|████████▏ | 41/50 [00:34<00:09,  1.05s/it]

[I 2025-12-07 15:20:08,142] Trial 40 finished with value: 0.2530612244897959 and parameters: {'n_estimators': 187, 'max_depth': 26, 'min_samples_split': 5, 'min_samples_leaf': 2, 'class_weight': 'balanced_subsample'}. Best is trial 33 with value: 0.2627118644067797.

Best trial: 33. Best value: 0.262712:  84%|████████▍ | 42/50 [00:35<00:07,  1.09it/s]

[I 2025-12-07 15:20:08,762] Trial 41 finished with value: 0.2542372881355932 and parameters: {'n_estimators': 155, 'max_depth': 24, 'min_samples_split': 5, 'min_samples_leaf': 2, 'class_weight': 'balanced'}. Best is trial 33 with value: 0.2627118644067797.

Best trial: 33. Best value: 0.262712:  86%|████████▌ | 43/50 [00:36<00:05,  1.20it/s]

[I 2025-12-07 15:20:09,401] Trial 42 finished with value: 0.24691358024691357 and parameters: {'n_estimators': 229, 'max_depth': 22, 'min_samples_split': 4, 'min_samples_leaf': 4, 'class_weight': 'balanced'}. Best is trial 33 with value: 0.2627118644067797.

Best trial: 33. Best value: 0.262712:  88%|████████▊ | 44/50 [00:36<00:04,  1.33it/s]

[I 2025-12-07 15:20:09,956] Trial 43 finished with value: 0.25203252032520324 and parameters: {'n_estimators': 211, 'max_depth': 30, 'min_samples_split': 7, 'min_samples_leaf': 2, 'class_weight': 'balanced'}. Best is trial 33 with value: 0.2627118644067797.

Best trial: 33. Best value: 0.262712:  90%|█████████ | 45/50 [00:37<00:03,  1.44it/s]

[I 2025-12-07 15:20:10,527] Trial 44 finished with value: 0.2553191489361702 and parameters: {'n_estimators': 251, 'max_depth': 16, 'min_samples_split': 6, 'min_samples_leaf': 1, 'class_weight': 'balanced'}. Best is trial 33 with value: 0.2627118644067797.

Best trial: 33. Best value: 0.262712:  92%|█████████▏| 46/50 [00:37<00:02,  1.51it/s]

[I 2025-12-07 15:20:11,103] Trial 45 finished with value: 0.25203252032520324 and parameters: {'n_estimators': 231, 'max_depth': 21, 'min_samples_split': 12, 'min_samples_leaf': 5, 'class_weight': 'balanced'}. Best is trial 33 with value: 0.2627118644067797.

Best trial: 33. Best value: 0.262712:  94%|█████████▍| 47/50 [00:38<00:02,  1.37it/s]

[I 2025-12-07 15:20:11,997] Trial 46 finished with value: 0.256198347107438 and parameters: {'n_estimators': 196, 'max_depth': 23, 'min_samples_split': 14, 'min_samples_leaf': 7, 'class_weight': 'balanced_subsample'}. Best is trial 33 with value: 0.2627118644067797.

Best trial: 33. Best value: 0.262712:  96%|█████████▌| 48/50 [00:39<00:01,  1.44it/s]

[I 2025-12-07 15:20:12,614] Trial 47 finished with value: 0.25101214574898784 and parameters: {'n_estimators': 173, 'max_depth': 26, 'min_samples_split': 7, 'min_samples_leaf': 2, 'class_weight': 'balanced_subsample'}. Best is trial 33 with value: 0.2627118644067797.

Best trial: 33. Best value: 0.262712:  98%|█████████▊| 49/50 [00:39<00:00,  1.54it/s]

[I 2025-12-07 15:20:13,161] Trial 48 finished with value: 0.25 and parameters: {'n_estimators': 259, 'max_depth': 20, 'min_samples_split': 3, 'min_samples_leaf': 3, 'class_weight': 'balanced'}. Best is trial 33 with value: 0.2627118644067797.

Best trial: 33. Best value: 0.262712: 100%|██████████| 50/50 [00:40<00:00,  1.23it/s]

[I 2025-12-07 15:20:13,949] Trial 49 finished with value: 0.2575107296137339 and parameters: {'n_estimators': 218, 'max_depth': 15, 'min_samples_split': 10, 'min_samples_leaf': 1, 'class_weight': 'balanced_subsample'}. Best is trial 33 with value: 0.2627118644067797.

In [17]:
print("Best F1:", study_rf.best_value)
print("Best params:", study_rf.best_params)

Best F1: 0.2627118644067797
Best params: {'n_estimators': 239, 'max_depth': 16, 'min_samples_split': 7, 'min_samples_leaf': 3, 'class_weight': 'balanced'}

In [18]:
best_params = study_rf.best_params

best_rf = RandomForestClassifier(
    **best_params,
    random_state=42,
    n_jobs=-1
)

best_rf.fit(X_train, y_train)

y_pred_best = best_rf.predict(X_test)

print(classification_report(y_test, y_pred_best))

              precision    recall  f1-score   support

           0       0.99      0.97      0.98      5376
           1       0.17      0.35      0.23        93

    accuracy                           0.96      5469
   macro avg       0.58      0.66      0.61      5469
weighted avg       0.97      0.96      0.97      5469

## RF + SMOTE + Hyperparameter Tuning

In [19]:
def objective_rf_smote(trial, X_train, y_train, X_val, y_val):
    n_estimators = trial.suggest_int("n_estimators", 50, 300)
    max_depth = trial.suggest_int("max_depth", 5, 30)
    min_samples_split = trial.suggest_int("min_samples_split", 2, 20)
    min_samples_leaf = trial.suggest_int("min_samples_leaf", 1, 10)
    class_weight = trial.suggest_categorical("class_weight",
                                             ["balanced", "balanced_subsample"])

    smote = SMOTE(sampling_strategy=0.3, random_state=42)
    X_train_res, y_train_res = smote.fit_resample(X_train, y_train)

    model = RandomForestClassifier(
        n_estimators=n_estimators,
        max_depth=max_depth,
        min_samples_split=min_samples_split,
        min_samples_leaf=min_samples_leaf,
        class_weight=class_weight,
        random_state=42,
        n_jobs=-1
    )

    model.fit(X_train_res, y_train_res)

    y_pred = model.predict(X_val)

    f1 = f1_score(y_val, y_pred)

    return f1

In [ ]:
study_rf_smote = optuna.create_study(
    study_name="rf_smote_opt",
    direction="maximize",
    storage="sqlite:///.../models/rf_smote.db",
    load_if_exists=True
)

[I 2025-12-07 15:20:14,648] A new study created in RDB with name: rf_smote_opt

In [21]:
study_rf_smote.optimize(lambda trial: objective_rf_smote(trial, X_train, y_train, X_val, y_val), n_trials=50, show_progress_bar=True)

Best trial: 0. Best value: 0.163842:   2%|▏         | 1/50 [00:00<00:30,  1.62it/s]

[I 2025-12-07 15:20:15,283] Trial 0 finished with value: 0.1638418079096045 and parameters: {'n_estimators': 110, 'max_depth': 24, 'min_samples_split': 16, 'min_samples_leaf': 6, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.1638418079096045.

Best trial: 0. Best value: 0.163842:   4%|▍         | 2/50 [00:01<00:28,  1.66it/s]

[I 2025-12-07 15:20:15,883] Trial 1 finished with value: 0.145 and parameters: {'n_estimators': 198, 'max_depth': 27, 'min_samples_split': 17, 'min_samples_leaf': 9, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.1638418079096045.

Best trial: 0. Best value: 0.163842:   6%|▌         | 3/50 [00:01<00:23,  1.99it/s]

[I 2025-12-07 15:20:16,265] Trial 2 finished with value: 0.11262135922330097 and parameters: {'n_estimators': 125, 'max_depth': 16, 'min_samples_split': 20, 'min_samples_leaf': 7, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.1638418079096045.

Best trial: 3. Best value: 0.168116:   8%|▊         | 4/50 [00:01<00:19,  2.32it/s]

[I 2025-12-07 15:20:16,586] Trial 3 finished with value: 0.1681159420289855 and parameters: {'n_estimators': 62, 'max_depth': 21, 'min_samples_split': 16, 'min_samples_leaf': 5, 'class_weight': 'balanced_subsample'}. Best is trial 3 with value: 0.1681159420289855.

Best trial: 3. Best value: 0.168116:  10%|█         | 5/50 [00:02<00:18,  2.42it/s]

[I 2025-12-07 15:20:16,970] Trial 4 finished with value: 0.08157099697885196 and parameters: {'n_estimators': 129, 'max_depth': 13, 'min_samples_split': 3, 'min_samples_leaf': 7, 'class_weight': 'balanced'}. Best is trial 3 with value: 0.1681159420289855.

Best trial: 5. Best value: 0.169014:  12%|█▏        | 6/50 [00:02<00:21,  2.04it/s]

[I 2025-12-07 15:20:17,607] Trial 5 finished with value: 0.16901408450704225 and parameters: {'n_estimators': 227, 'max_depth': 26, 'min_samples_split': 13, 'min_samples_leaf': 7, 'class_weight': 'balanced'}. Best is trial 5 with value: 0.16901408450704225.

Best trial: 6. Best value: 0.194357:  14%|█▍        | 7/50 [00:03<00:23,  1.81it/s]

[I 2025-12-07 15:20:18,288] Trial 6 finished with value: 0.19435736677115986 and parameters: {'n_estimators': 220, 'max_depth': 23, 'min_samples_split': 3, 'min_samples_leaf': 5, 'class_weight': 'balanced'}. Best is trial 6 with value: 0.19435736677115986.

Best trial: 6. Best value: 0.194357:  16%|█▌        | 8/50 [00:04<00:21,  1.95it/s]

[I 2025-12-07 15:20:18,720] Trial 7 finished with value: 0.1411764705882353 and parameters: {'n_estimators': 80, 'max_depth': 17, 'min_samples_split': 17, 'min_samples_leaf': 2, 'class_weight': 'balanced_subsample'}. Best is trial 6 with value: 0.19435736677115986.

Best trial: 6. Best value: 0.194357:  18%|█▊        | 9/50 [00:05<00:26,  1.52it/s]

[I 2025-12-07 15:20:19,692] Trial 8 finished with value: 0.10074626865671642 and parameters: {'n_estimators': 205, 'max_depth': 15, 'min_samples_split': 15, 'min_samples_leaf': 5, 'class_weight': 'balanced_subsample'}. Best is trial 6 with value: 0.19435736677115986.

Best trial: 6. Best value: 0.194357:  20%|██        | 10/50 [00:08<00:57,  1.43s/it]

[I 2025-12-07 15:20:22,826] Trial 9 finished with value: 0.10404624277456648 and parameters: {'n_estimators': 277, 'max_depth': 15, 'min_samples_split': 6, 'min_samples_leaf': 4, 'class_weight': 'balanced_subsample'}. Best is trial 6 with value: 0.19435736677115986.

Best trial: 6. Best value: 0.194357:  22%|██▏       | 11/50 [00:09<00:55,  1.43s/it]

[I 2025-12-07 15:20:24,274] Trial 10 finished with value: 0.03825857519788918 and parameters: {'n_estimators': 299, 'max_depth': 6, 'min_samples_split': 9, 'min_samples_leaf': 1, 'class_weight': 'balanced'}. Best is trial 6 with value: 0.19435736677115986.

Best trial: 6. Best value: 0.194357:  24%|██▍       | 12/50 [00:11<00:56,  1.48s/it]

[I 2025-12-07 15:20:25,870] Trial 11 finished with value: 0.13875598086124402 and parameters: {'n_estimators': 241, 'max_depth': 29, 'min_samples_split': 11, 'min_samples_leaf': 10, 'class_weight': 'balanced'}. Best is trial 6 with value: 0.19435736677115986.

Best trial: 12. Best value: 0.210145:  26%|██▌       | 13/50 [00:12<00:57,  1.55s/it]

[I 2025-12-07 15:20:27,580] Trial 12 finished with value: 0.21014492753623187 and parameters: {'n_estimators': 237, 'max_depth': 22, 'min_samples_split': 2, 'min_samples_leaf': 3, 'class_weight': 'balanced'}. Best is trial 12 with value: 0.21014492753623187.

Best trial: 12. Best value: 0.210145:  28%|██▊       | 14/50 [00:14<00:51,  1.44s/it]

[I 2025-12-07 15:20:28,743] Trial 13 finished with value: 0.20689655172413793 and parameters: {'n_estimators': 162, 'max_depth': 21, 'min_samples_split': 2, 'min_samples_leaf': 3, 'class_weight': 'balanced'}. Best is trial 12 with value: 0.21014492753623187.

Best trial: 12. Best value: 0.210145:  30%|███       | 15/50 [00:14<00:44,  1.27s/it]

[I 2025-12-07 15:20:29,632] Trial 14 finished with value: 0.20477815699658702 and parameters: {'n_estimators': 156, 'max_depth': 21, 'min_samples_split': 6, 'min_samples_leaf': 3, 'class_weight': 'balanced'}. Best is trial 12 with value: 0.21014492753623187.

Best trial: 12. Best value: 0.210145:  32%|███▏      | 16/50 [00:15<00:38,  1.12s/it]

[I 2025-12-07 15:20:30,419] Trial 15 finished with value: 0.19292604501607716 and parameters: {'n_estimators': 171, 'max_depth': 20, 'min_samples_split': 2, 'min_samples_leaf': 3, 'class_weight': 'balanced'}. Best is trial 12 with value: 0.21014492753623187.

Best trial: 12. Best value: 0.210145:  34%|███▍      | 17/50 [00:16<00:32,  1.02it/s]

[I 2025-12-07 15:20:31,086] Trial 16 finished with value: 0.05074365704286964 and parameters: {'n_estimators': 255, 'max_depth': 8, 'min_samples_split': 6, 'min_samples_leaf': 1, 'class_weight': 'balanced'}. Best is trial 12 with value: 0.21014492753623187.

Best trial: 12. Best value: 0.210145:  36%|███▌      | 18/50 [00:16<00:26,  1.20it/s]

[I 2025-12-07 15:20:31,576] Trial 17 finished with value: 0.069221260815822 and parameters: {'n_estimators': 179, 'max_depth': 11, 'min_samples_split': 9, 'min_samples_leaf': 3, 'class_weight': 'balanced'}. Best is trial 12 with value: 0.21014492753623187.

Best trial: 12. Best value: 0.210145:  38%|███▊      | 19/50 [00:17<00:24,  1.24it/s]

[I 2025-12-07 15:20:32,305] Trial 18 finished with value: 0.1895424836601307 and parameters: {'n_estimators': 151, 'max_depth': 19, 'min_samples_split': 4, 'min_samples_leaf': 2, 'class_weight': 'balanced_subsample'}. Best is trial 12 with value: 0.21014492753623187.

Best trial: 12. Best value: 0.210145:  40%|████      | 20/50 [00:18<00:23,  1.26it/s]

[I 2025-12-07 15:20:33,074] Trial 19 finished with value: 0.2 and parameters: {'n_estimators': 263, 'max_depth': 30, 'min_samples_split': 5, 'min_samples_leaf': 4, 'class_weight': 'balanced'}. Best is trial 12 with value: 0.21014492753623187.

Best trial: 20. Best value: 0.240964:  42%|████▏     | 21/50 [00:18<00:21,  1.38it/s]

[I 2025-12-07 15:20:33,638] Trial 20 finished with value: 0.24096385542168675 and parameters: {'n_estimators': 188, 'max_depth': 23, 'min_samples_split': 8, 'min_samples_leaf': 2, 'class_weight': 'balanced'}. Best is trial 20 with value: 0.24096385542168675.

Best trial: 20. Best value: 0.240964:  44%|████▍     | 22/50 [00:19<00:19,  1.47it/s]

[I 2025-12-07 15:20:34,222] Trial 21 finished with value: 0.23387096774193547 and parameters: {'n_estimators': 195, 'max_depth': 24, 'min_samples_split': 8, 'min_samples_leaf': 2, 'class_weight': 'balanced'}. Best is trial 20 with value: 0.24096385542168675.

Best trial: 20. Best value: 0.240964:  46%|████▌     | 23/50 [00:20<00:18,  1.43it/s]

[I 2025-12-07 15:20:34,964] Trial 22 finished with value: 0.23387096774193547 and parameters: {'n_estimators': 195, 'max_depth': 24, 'min_samples_split': 8, 'min_samples_leaf': 2, 'class_weight': 'balanced'}. Best is trial 20 with value: 0.24096385542168675.

Best trial: 23. Best value: 0.262443:  48%|████▊     | 24/50 [00:20<00:17,  1.50it/s]

[I 2025-12-07 15:20:35,551] Trial 23 finished with value: 0.26244343891402716 and parameters: {'n_estimators': 199, 'max_depth': 25, 'min_samples_split': 8, 'min_samples_leaf': 1, 'class_weight': 'balanced'}. Best is trial 23 with value: 0.26244343891402716.

Best trial: 23. Best value: 0.262443:  50%|█████     | 25/50 [00:21<00:15,  1.57it/s]

[I 2025-12-07 15:20:36,125] Trial 24 finished with value: 0.24892703862660945 and parameters: {'n_estimators': 189, 'max_depth': 25, 'min_samples_split': 11, 'min_samples_leaf': 1, 'class_weight': 'balanced'}. Best is trial 23 with value: 0.26244343891402716.

Best trial: 23. Best value: 0.262443:  52%|█████▏    | 26/50 [00:22<00:15,  1.55it/s]

[I 2025-12-07 15:20:36,790] Trial 25 finished with value: 0.26126126126126126 and parameters: {'n_estimators': 218, 'max_depth': 27, 'min_samples_split': 11, 'min_samples_leaf': 1, 'class_weight': 'balanced'}. Best is trial 23 with value: 0.26244343891402716.

Best trial: 23. Best value: 0.262443:  54%|█████▍    | 27/50 [00:23<00:17,  1.31it/s]

[I 2025-12-07 15:20:37,830] Trial 26 finished with value: 0.24892703862660945 and parameters: {'n_estimators': 214, 'max_depth': 27, 'min_samples_split': 12, 'min_samples_leaf': 1, 'class_weight': 'balanced_subsample'}. Best is trial 23 with value: 0.26244343891402716.

Best trial: 23. Best value: 0.262443:  56%|█████▌    | 28/50 [00:23<00:14,  1.49it/s]

[I 2025-12-07 15:20:38,279] Trial 27 finished with value: 0.24892703862660945 and parameters: {'n_estimators': 139, 'max_depth': 28, 'min_samples_split': 13, 'min_samples_leaf': 1, 'class_weight': 'balanced'}. Best is trial 23 with value: 0.26244343891402716.

Best trial: 23. Best value: 0.262443:  58%|█████▊    | 29/50 [00:24<00:15,  1.36it/s]

[I 2025-12-07 15:20:39,176] Trial 28 finished with value: 0.25 and parameters: {'n_estimators': 248, 'max_depth': 26, 'min_samples_split': 10, 'min_samples_leaf': 1, 'class_weight': 'balanced'}. Best is trial 23 with value: 0.26244343891402716.

Best trial: 23. Best value: 0.262443:  60%|██████    | 30/50 [00:25<00:15,  1.27it/s]

[I 2025-12-07 15:20:40,079] Trial 29 finished with value: 0.19931271477663232 and parameters: {'n_estimators': 288, 'max_depth': 30, 'min_samples_split': 10, 'min_samples_leaf': 4, 'class_weight': 'balanced'}. Best is trial 23 with value: 0.26244343891402716.

Best trial: 23. Best value: 0.262443:  62%|██████▏   | 31/50 [00:26<00:15,  1.26it/s]

[I 2025-12-07 15:20:40,885] Trial 30 finished with value: 0.24166666666666667 and parameters: {'n_estimators': 246, 'max_depth': 26, 'min_samples_split': 14, 'min_samples_leaf': 1, 'class_weight': 'balanced'}. Best is trial 23 with value: 0.26244343891402716.

Best trial: 23. Best value: 0.262443:  64%|██████▍   | 32/50 [00:26<00:13,  1.33it/s]

[I 2025-12-07 15:20:41,550] Trial 31 finished with value: 0.2413793103448276 and parameters: {'n_estimators': 221, 'max_depth': 25, 'min_samples_split': 11, 'min_samples_leaf': 1, 'class_weight': 'balanced'}. Best is trial 23 with value: 0.26244343891402716.

Best trial: 23. Best value: 0.262443:  66%|██████▌   | 33/50 [00:27<00:13,  1.30it/s]

[I 2025-12-07 15:20:42,345] Trial 32 finished with value: 0.23868312757201646 and parameters: {'n_estimators': 266, 'max_depth': 28, 'min_samples_split': 10, 'min_samples_leaf': 2, 'class_weight': 'balanced'}. Best is trial 23 with value: 0.26244343891402716.

Best trial: 23. Best value: 0.262443:  68%|██████▊   | 34/50 [00:28<00:11,  1.38it/s]

[I 2025-12-07 15:20:42,978] Trial 33 finished with value: 0.2510460251046025 and parameters: {'n_estimators': 209, 'max_depth': 25, 'min_samples_split': 12, 'min_samples_leaf': 1, 'class_weight': 'balanced'}. Best is trial 23 with value: 0.26244343891402716.

Best trial: 23. Best value: 0.262443:  70%|███████   | 35/50 [00:28<00:10,  1.44it/s]

[I 2025-12-07 15:20:43,599] Trial 34 finished with value: 0.20422535211267606 and parameters: {'n_estimators': 211, 'max_depth': 27, 'min_samples_split': 19, 'min_samples_leaf': 2, 'class_weight': 'balanced'}. Best is trial 23 with value: 0.26244343891402716.

Best trial: 23. Best value: 0.262443:  72%|███████▏  | 36/50 [00:29<00:09,  1.46it/s]

[I 2025-12-07 15:20:44,264] Trial 35 finished with value: 0.18404907975460122 and parameters: {'n_estimators': 234, 'max_depth': 19, 'min_samples_split': 13, 'min_samples_leaf': 1, 'class_weight': 'balanced'}. Best is trial 23 with value: 0.26244343891402716.

Best trial: 23. Best value: 0.262443:  74%|███████▍  | 37/50 [00:30<00:08,  1.45it/s]

[I 2025-12-07 15:20:44,957] Trial 36 finished with value: 0.15025906735751296 and parameters: {'n_estimators': 248, 'max_depth': 26, 'min_samples_split': 7, 'min_samples_leaf': 8, 'class_weight': 'balanced'}. Best is trial 23 with value: 0.26244343891402716.

Best trial: 23. Best value: 0.262443:  76%|███████▌  | 38/50 [00:30<00:07,  1.71it/s]

[I 2025-12-07 15:20:45,300] Trial 37 finished with value: 0.23715415019762845 and parameters: {'n_estimators': 108, 'max_depth': 28, 'min_samples_split': 12, 'min_samples_leaf': 2, 'class_weight': 'balanced'}. Best is trial 23 with value: 0.26244343891402716.

Best trial: 23. Best value: 0.262443:  78%|███████▊  | 39/50 [00:31<00:07,  1.39it/s]

[I 2025-12-07 15:20:46,333] Trial 38 finished with value: 0.1751412429378531 and parameters: {'n_estimators': 229, 'max_depth': 23, 'min_samples_split': 15, 'min_samples_leaf': 6, 'class_weight': 'balanced_subsample'}. Best is trial 23 with value: 0.26244343891402716.

Best trial: 39. Best value: 0.263158:  80%|████████  | 40/50 [00:32<00:06,  1.45it/s]

[I 2025-12-07 15:20:46,947] Trial 39 finished with value: 0.2631578947368421 and parameters: {'n_estimators': 206, 'max_depth': 25, 'min_samples_split': 10, 'min_samples_leaf': 1, 'class_weight': 'balanced'}. Best is trial 39 with value: 0.2631578947368421.

Best trial: 39. Best value: 0.263158:  82%|████████▏ | 41/50 [00:33<00:06,  1.37it/s]

[I 2025-12-07 15:20:47,783] Trial 40 finished with value: 0.15633423180592992 and parameters: {'n_estimators': 176, 'max_depth': 18, 'min_samples_split': 9, 'min_samples_leaf': 3, 'class_weight': 'balanced_subsample'}. Best is trial 39 with value: 0.2631578947368421.

Best trial: 39. Best value: 0.263158:  84%|████████▍ | 42/50 [00:33<00:05,  1.43it/s]

[I 2025-12-07 15:20:48,401] Trial 41 finished with value: 0.2631578947368421 and parameters: {'n_estimators': 204, 'max_depth': 25, 'min_samples_split': 10, 'min_samples_leaf': 1, 'class_weight': 'balanced'}. Best is trial 39 with value: 0.2631578947368421.

Best trial: 39. Best value: 0.263158:  86%|████████▌ | 43/50 [00:34<00:04,  1.49it/s]

[I 2025-12-07 15:20:49,011] Trial 42 finished with value: 0.23770491803278687 and parameters: {'n_estimators': 205, 'max_depth': 24, 'min_samples_split': 12, 'min_samples_leaf': 1, 'class_weight': 'balanced'}. Best is trial 39 with value: 0.2631578947368421.

Best trial: 39. Best value: 0.263158:  88%|████████▊ | 44/50 [00:34<00:03,  1.55it/s]

[I 2025-12-07 15:20:49,599] Trial 43 finished with value: 0.22641509433962265 and parameters: {'n_estimators': 204, 'max_depth': 22, 'min_samples_split': 10, 'min_samples_leaf': 2, 'class_weight': 'balanced'}. Best is trial 39 with value: 0.2631578947368421.

Best trial: 39. Best value: 0.263158:  90%|█████████ | 45/50 [00:35<00:03,  1.56it/s]

[I 2025-12-07 15:20:50,225] Trial 44 finished with value: 0.1554959785522788 and parameters: {'n_estimators': 222, 'max_depth': 25, 'min_samples_split': 14, 'min_samples_leaf': 8, 'class_weight': 'balanced'}. Best is trial 39 with value: 0.2631578947368421.

Best trial: 39. Best value: 0.263158:  92%|█████████▏| 46/50 [00:36<00:02,  1.64it/s]

[I 2025-12-07 15:20:50,759] Trial 45 finished with value: 0.2543859649122807 and parameters: {'n_estimators': 180, 'max_depth': 22, 'min_samples_split': 7, 'min_samples_leaf': 1, 'class_weight': 'balanced'}. Best is trial 39 with value: 0.2631578947368421.

Best trial: 39. Best value: 0.263158:  94%|█████████▍| 47/50 [00:36<00:01,  1.70it/s]

[I 2025-12-07 15:20:51,299] Trial 46 finished with value: 0.2230769230769231 and parameters: {'n_estimators': 178, 'max_depth': 22, 'min_samples_split': 7, 'min_samples_leaf': 2, 'class_weight': 'balanced'}. Best is trial 39 with value: 0.2631578947368421.

Best trial: 39. Best value: 0.263158:  96%|█████████▌| 48/50 [00:37<00:01,  1.71it/s]

[I 2025-12-07 15:20:51,875] Trial 47 finished with value: 0.2140221402214022 and parameters: {'n_estimators': 187, 'max_depth': 29, 'min_samples_split': 7, 'min_samples_leaf': 4, 'class_weight': 'balanced'}. Best is trial 39 with value: 0.2631578947368421.

Best trial: 39. Best value: 0.263158:  98%|█████████▊| 49/50 [00:37<00:00,  1.81it/s]

[I 2025-12-07 15:20:52,357] Trial 48 finished with value: 0.1377672209026128 and parameters: {'n_estimators': 163, 'max_depth': 27, 'min_samples_split': 5, 'min_samples_leaf': 10, 'class_weight': 'balanced'}. Best is trial 39 with value: 0.2631578947368421.

Best trial: 39. Best value: 0.263158: 100%|██████████| 50/50 [00:38<00:00,  1.30it/s]

[I 2025-12-07 15:20:53,067] Trial 49 finished with value: 0.20863309352517986 and parameters: {'n_estimators': 142, 'max_depth': 20, 'min_samples_split': 9, 'min_samples_leaf': 1, 'class_weight': 'balanced_subsample'}. Best is trial 39 with value: 0.2631578947368421.

In [22]:
best_params = study_rf_smote.best_params

smote = SMOTE(sampling_strategy=0.3, random_state=42)
X_train_res, y_train_res = smote.fit_resample(X_train, y_train)

final_rf_smote = RandomForestClassifier(
    **best_params,
    random_state=42,
    n_jobs=-1
)

final_rf_smote.fit(X_train_res, y_train_res)

RandomForestClassifier(class_weight='balanced', max_depth=25,
                       min_samples_split=10, n_estimators=206, n_jobs=-1,
                       random_state=42)

In [23]:
y_pred_test = final_rf_smote.predict(X_test)
print(classification_report(y_test, y_pred_test))

              precision    recall  f1-score   support

           0       0.99      0.98      0.98      5376
           1       0.19      0.32      0.24        93

    accuracy                           0.97      5469
   macro avg       0.59      0.65      0.61      5469
weighted avg       0.97      0.97      0.97      5469

# XGBOOST CLASSIFIER

## XGBOOST + Hyperparameter Tuning

In [ ]:
def objective_xgb(trial, X_train, y_train, X_val, y_val):

    params = {
        "learning_rate": trial.suggest_float("learning_rate", 0.01, 0.3),
        "max_depth": trial.suggest_int("max_depth", 3, 12),
        "n_estimators": trial.suggest_int("n_estimators", 200, 800),
        "subsample": trial.suggest_float("subsample", 0.6, 1.0),
        "colsample_bytree": trial.suggest_float("colsample_bytree", 0.6, 1.0),
        "gamma": trial.suggest_float("gamma", 0, 10),
        "min_child_weight": trial.suggest_int("min_child_weight", 1, 30),        
        "scale_pos_weight": trial.suggest_float("scale_pos_weight", 1, 50),
        "eval_metric": "logloss",
        "random_state": 42,
        "n_jobs": -1,
        "tree_method": "hist",
    }

    model = XGBClassifier(**params)
    model.fit(X_train, y_train)

    y_pred_val = model.predict(X_val)

    return f1_score(y_val, y_pred_val)

In [ ]:
study_xgb = optuna.create_study(
    study_name="xgb_class_opt",
    direction="maximize",
    storage="sqlite:///.../models/gb_class.db",
    load_if_exists=True
)

study_xgb.optimize(lambda trial: objective_xgb(trial, X_train, y_train, X_val, y_val), n_trials=50, show_progress_bar=True)

[I 2025-12-07 15:20:53,966] A new study created in RDB with name: xgb_class_opt
Best trial: 0. Best value: 0.267176:   2%|▏         | 1/50 [00:01<01:08,  1.41s/it]

[I 2025-12-07 15:20:55,375] Trial 0 finished with value: 0.26717557251908397 and parameters: {'learning_rate': 0.12635809447385093, 'max_depth': 10, 'n_estimators': 480, 'subsample': 0.7083475220610644, 'colsample_bytree': 0.9546246644165886, 'gamma': 2.0796519428272884, 'min_child_weight': 3, 'scale_pos_weight': 45.951508768263764}. Best is trial 0 with value: 0.26717557251908397.

Best trial: 0. Best value: 0.267176:   4%|▍         | 2/50 [00:01<00:35,  1.37it/s]

[I 2025-12-07 15:20:55,637] Trial 1 finished with value: 0.02040816326530612 and parameters: {'learning_rate': 0.19637384604421604, 'max_depth': 7, 'n_estimators': 562, 'subsample': 0.8621427648541132, 'colsample_bytree': 0.7427823632614743, 'gamma': 8.026746255123333, 'min_child_weight': 10, 'scale_pos_weight': 3.6716785576455995}. Best is trial 0 with value: 0.26717557251908397.

Best trial: 0. Best value: 0.267176:   6%|▌         | 3/50 [00:02<00:32,  1.45it/s]

[I 2025-12-07 15:20:56,278] Trial 2 finished with value: 0.254071661237785 and parameters: {'learning_rate': 0.23147478798140117, 'max_depth': 5, 'n_estimators': 700, 'subsample': 0.8846019919305227, 'colsample_bytree': 0.660182753806134, 'gamma': 3.318369138844951, 'min_child_weight': 19, 'scale_pos_weight': 30.50136668356796}. Best is trial 0 with value: 0.26717557251908397.

Best trial: 0. Best value: 0.267176:   8%|▊         | 4/50 [00:03<00:38,  1.20it/s]

[I 2025-12-07 15:20:57,327] Trial 3 finished with value: 0.25517241379310346 and parameters: {'learning_rate': 0.1825532506954101, 'max_depth': 12, 'n_estimators': 799, 'subsample': 0.7169875189288851, 'colsample_bytree': 0.7535496765110438, 'gamma': 5.715042160728209, 'min_child_weight': 17, 'scale_pos_weight': 45.95132024022546}. Best is trial 0 with value: 0.26717557251908397.

Best trial: 0. Best value: 0.267176:  10%|█         | 5/50 [00:03<00:30,  1.49it/s]

[I 2025-12-07 15:20:57,708] Trial 4 finished with value: 0.2315112540192926 and parameters: {'learning_rate': 0.23225549283319874, 'max_depth': 10, 'n_estimators': 503, 'subsample': 0.8069967062287454, 'colsample_bytree': 0.746798780897609, 'gamma': 9.810068092330452, 'min_child_weight': 26, 'scale_pos_weight': 27.065169088257775}. Best is trial 0 with value: 0.26717557251908397.

Best trial: 0. Best value: 0.267176:  12%|█▏        | 6/50 [00:04<00:23,  1.86it/s]

[I 2025-12-07 15:20:57,991] Trial 5 finished with value: 0.1437908496732026 and parameters: {'learning_rate': 0.1093338566823388, 'max_depth': 3, 'n_estimators': 335, 'subsample': 0.910495240450365, 'colsample_bytree': 0.9205066573418447, 'gamma': 2.893034204389806, 'min_child_weight': 18, 'scale_pos_weight': 26.536013124195723}. Best is trial 0 with value: 0.26717557251908397.

Best trial: 6. Best value: 0.290749:  14%|█▍        | 7/50 [00:04<00:20,  2.06it/s]

[I 2025-12-07 15:20:58,363] Trial 6 finished with value: 0.2907488986784141 and parameters: {'learning_rate': 0.053349602531775175, 'max_depth': 10, 'n_estimators': 319, 'subsample': 0.8599867581759246, 'colsample_bytree': 0.6021939703475563, 'gamma': 8.22407289468693, 'min_child_weight': 7, 'scale_pos_weight': 23.19379239904478}. Best is trial 6 with value: 0.2907488986784141.

Best trial: 6. Best value: 0.290749:  16%|█▌        | 8/50 [00:05<00:22,  1.84it/s]

[I 2025-12-07 15:20:59,037] Trial 7 finished with value: 0.1896551724137931 and parameters: {'learning_rate': 0.2095658561933141, 'max_depth': 3, 'n_estimators': 769, 'subsample': 0.9647682168033384, 'colsample_bytree': 0.8792192204045809, 'gamma': 0.3226498252393595, 'min_child_weight': 27, 'scale_pos_weight': 4.001874083519515}. Best is trial 6 with value: 0.2907488986784141.

Best trial: 6. Best value: 0.290749:  18%|█▊        | 9/50 [00:07<00:46,  1.12s/it]

[I 2025-12-07 15:21:01,421] Trial 8 finished with value: 0.26277372262773724 and parameters: {'learning_rate': 0.2499121069311134, 'max_depth': 9, 'n_estimators': 730, 'subsample': 0.7951147875219624, 'colsample_bytree': 0.9215347773793957, 'gamma': 5.617483513834739, 'min_child_weight': 10, 'scale_pos_weight': 46.78338998515685}. Best is trial 6 with value: 0.2907488986784141.

Best trial: 6. Best value: 0.290749:  20%|██        | 10/50 [00:09<00:53,  1.34s/it]

[I 2025-12-07 15:21:03,259] Trial 9 finished with value: 0.28112449799196787 and parameters: {'learning_rate': 0.035232368018302485, 'max_depth': 10, 'n_estimators': 251, 'subsample': 0.6058033883932127, 'colsample_bytree': 0.7497012510160075, 'gamma': 1.8989008363172144, 'min_child_weight': 25, 'scale_pos_weight': 27.140912197580313}. Best is trial 6 with value: 0.2907488986784141.

Best trial: 6. Best value: 0.290749:  22%|██▏       | 11/50 [00:09<00:41,  1.06s/it]

[I 2025-12-07 15:21:03,678] Trial 10 finished with value: 0.19117647058823528 and parameters: {'learning_rate': 0.03421654857056966, 'max_depth': 12, 'n_estimators': 203, 'subsample': 0.9986186167199714, 'colsample_bytree': 0.610886735054425, 'gamma': 7.8190493893431405, 'min_child_weight': 1, 'scale_pos_weight': 13.607286909638248}. Best is trial 6 with value: 0.2907488986784141.

Best trial: 6. Best value: 0.290749:  24%|██▍       | 12/50 [00:11<00:49,  1.30s/it]

[I 2025-12-07 15:21:05,523] Trial 11 finished with value: 0.16374269005847952 and parameters: {'learning_rate': 0.031385291135746174, 'max_depth': 8, 'n_estimators': 218, 'subsample': 0.6111994063639897, 'colsample_bytree': 0.8246664618384848, 'gamma': 0.2989783206820966, 'min_child_weight': 30, 'scale_pos_weight': 16.755715346520667}. Best is trial 6 with value: 0.2907488986784141.

Best trial: 6. Best value: 0.290749:  26%|██▌       | 13/50 [00:13<00:51,  1.38s/it]

[I 2025-12-07 15:21:07,098] Trial 12 finished with value: 0.275092936802974 and parameters: {'learning_rate': 0.0749299357673256, 'max_depth': 10, 'n_estimators': 308, 'subsample': 0.604301950970914, 'colsample_bytree': 0.6678577243340144, 'gamma': 4.164161639695955, 'min_child_weight': 9, 'scale_pos_weight': 33.93126485664896}. Best is trial 6 with value: 0.2907488986784141.

Best trial: 6. Best value: 0.290749:  28%|██▊       | 14/50 [00:13<00:40,  1.14s/it]

[I 2025-12-07 15:21:07,672] Trial 13 finished with value: 0.26373626373626374 and parameters: {'learning_rate': 0.2979995949313783, 'max_depth': 7, 'n_estimators': 344, 'subsample': 0.6950709175933972, 'colsample_bytree': 0.6007604960689485, 'gamma': 7.232892932996689, 'min_child_weight': 23, 'scale_pos_weight': 18.41870885575878}. Best is trial 6 with value: 0.2907488986784141.

Best trial: 6. Best value: 0.290749:  30%|███       | 15/50 [00:15<00:41,  1.19s/it]

[I 2025-12-07 15:21:08,969] Trial 14 finished with value: 0.25 and parameters: {'learning_rate': 0.010536556113556222, 'max_depth': 11, 'n_estimators': 407, 'subsample': 0.7928409895724385, 'colsample_bytree': 0.6871969149642961, 'gamma': 9.036969104499294, 'min_child_weight': 6, 'scale_pos_weight': 36.70472499134847}. Best is trial 6 with value: 0.2907488986784141.

Best trial: 15. Best value: 0.309524:  32%|███▏      | 16/50 [00:15<00:34,  1.01s/it]

[I 2025-12-07 15:21:09,544] Trial 15 finished with value: 0.30952380952380953 and parameters: {'learning_rate': 0.07038948259013245, 'max_depth': 8, 'n_estimators': 261, 'subsample': 0.6584569904564506, 'colsample_bytree': 0.8226837590504542, 'gamma': 6.688340756275187, 'min_child_weight': 13, 'scale_pos_weight': 21.05947030697943}. Best is trial 15 with value: 0.30952380952380953.

Best trial: 15. Best value: 0.309524:  34%|███▍      | 17/50 [00:17<00:40,  1.23s/it]

[I 2025-12-07 15:21:11,300] Trial 16 finished with value: 0.24096385542168675 and parameters: {'learning_rate': 0.07065893504273153, 'max_depth': 6, 'n_estimators': 414, 'subsample': 0.7477707184283329, 'colsample_bytree': 0.8381291025118318, 'gamma': 6.565924746376891, 'min_child_weight': 14, 'scale_pos_weight': 10.581521459340241}. Best is trial 15 with value: 0.30952380952380953.

Best trial: 15. Best value: 0.309524:  36%|███▌      | 18/50 [00:18<00:39,  1.24s/it]

[I 2025-12-07 15:21:12,552] Trial 17 finished with value: 0.2845528455284553 and parameters: {'learning_rate': 0.08651514309272229, 'max_depth': 8, 'n_estimators': 283, 'subsample': 0.6643466808553492, 'colsample_bytree': 0.992214173147425, 'gamma': 8.802210630462325, 'min_child_weight': 13, 'scale_pos_weight': 19.97691595357328}. Best is trial 15 with value: 0.30952380952380953.

Best trial: 15. Best value: 0.309524:  38%|███▊      | 19/50 [00:19<00:33,  1.08s/it]

[I 2025-12-07 15:21:13,289] Trial 18 finished with value: 0.21468926553672316 and parameters: {'learning_rate': 0.1374746481925896, 'max_depth': 5, 'n_estimators': 388, 'subsample': 0.8418342139356517, 'colsample_bytree': 0.799925344649911, 'gamma': 6.328556404291294, 'min_child_weight': 6, 'scale_pos_weight': 37.81967940972574}. Best is trial 15 with value: 0.30952380952380953.

Best trial: 15. Best value: 0.309524:  40%|████      | 20/50 [00:19<00:28,  1.05it/s]

[I 2025-12-07 15:21:13,951] Trial 19 finished with value: 0.2948207171314741 and parameters: {'learning_rate': 0.06540498140612055, 'max_depth': 9, 'n_estimators': 600, 'subsample': 0.9222306090520028, 'colsample_bytree': 0.7898963028632431, 'gamma': 4.571718180062787, 'min_child_weight': 6, 'scale_pos_weight': 22.990128657325144}. Best is trial 15 with value: 0.30952380952380953.

Best trial: 15. Best value: 0.309524:  42%|████▏     | 21/50 [00:20<00:23,  1.25it/s]

[I 2025-12-07 15:21:14,392] Trial 20 finished with value: 0.2465753424657534 and parameters: {'learning_rate': 0.10105742681299675, 'max_depth': 9, 'n_estimators': 639, 'subsample': 0.9051129274128504, 'colsample_bytree': 0.8677200180283609, 'gamma': 3.8743012130260825, 'min_child_weight': 13, 'scale_pos_weight': 8.610405768549896}. Best is trial 15 with value: 0.30952380952380953.

Best trial: 15. Best value: 0.309524:  44%|████▍     | 22/50 [00:20<00:18,  1.48it/s]

[I 2025-12-07 15:21:14,778] Trial 21 finished with value: 0.3063063063063063 and parameters: {'learning_rate': 0.06143872633267083, 'max_depth': 9, 'n_estimators': 604, 'subsample': 0.9600801030162833, 'colsample_bytree': 0.7839842133843549, 'gamma': 4.550377297270426, 'min_child_weight': 7, 'scale_pos_weight': 21.66570730032951}. Best is trial 15 with value: 0.30952380952380953.

Best trial: 15. Best value: 0.309524:  46%|████▌     | 23/50 [00:21<00:15,  1.76it/s]

[I 2025-12-07 15:21:15,095] Trial 22 finished with value: 0.3070539419087137 and parameters: {'learning_rate': 0.15454517897594894, 'max_depth': 9, 'n_estimators': 591, 'subsample': 0.9477440578633718, 'colsample_bytree': 0.7908214315780361, 'gamma': 4.774432946316749, 'min_child_weight': 3, 'scale_pos_weight': 21.511479920456157}. Best is trial 15 with value: 0.30952380952380953.

Best trial: 15. Best value: 0.309524:  48%|████▊     | 24/50 [00:21<00:12,  2.02it/s]

[I 2025-12-07 15:21:15,417] Trial 23 finished with value: 0.28 and parameters: {'learning_rate': 0.14599175889942279, 'max_depth': 8, 'n_estimators': 651, 'subsample': 0.9486296714032464, 'colsample_bytree': 0.7835366655783341, 'gamma': 4.9792605345235375, 'min_child_weight': 3, 'scale_pos_weight': 15.686614474537791}. Best is trial 15 with value: 0.30952380952380953.

Best trial: 15. Best value: 0.309524:  50%|█████     | 25/50 [00:21<00:10,  2.40it/s]

[I 2025-12-07 15:21:15,651] Trial 24 finished with value: 0.1564245810055866 and parameters: {'learning_rate': 0.1707493250273764, 'max_depth': 6, 'n_estimators': 529, 'subsample': 0.9901226418124285, 'colsample_bytree': 0.7031388694587523, 'gamma': 6.6140923852082505, 'min_child_weight': 3, 'scale_pos_weight': 21.75801072143721}. Best is trial 15 with value: 0.30952380952380953.

Best trial: 15. Best value: 0.309524:  52%|█████▏    | 26/50 [00:21<00:08,  2.69it/s]

[I 2025-12-07 15:21:15,916] Trial 25 finished with value: 0.2138364779874214 and parameters: {'learning_rate': 0.11976999693901624, 'max_depth': 9, 'n_estimators': 462, 'subsample': 0.952905435156381, 'colsample_bytree': 0.8276600156445529, 'gamma': 5.1061479418860705, 'min_child_weight': 11, 'scale_pos_weight': 11.569864617320928}. Best is trial 15 with value: 0.30952380952380953.

Best trial: 15. Best value: 0.309524:  54%|█████▍    | 27/50 [00:23<00:13,  1.72it/s]

[I 2025-12-07 15:21:16,988] Trial 26 finished with value: 0.2846153846153846 and parameters: {'learning_rate': 0.15798055789974125, 'max_depth': 11, 'n_estimators': 573, 'subsample': 0.6563937078686906, 'colsample_bytree': 0.8559247301955771, 'gamma': 5.968411629816739, 'min_child_weight': 1, 'scale_pos_weight': 30.23861107493878}. Best is trial 15 with value: 0.30952380952380953.

Best trial: 15. Best value: 0.309524:  56%|█████▌    | 28/50 [00:23<00:13,  1.66it/s]

[I 2025-12-07 15:21:17,636] Trial 27 finished with value: 0.30327868852459017 and parameters: {'learning_rate': 0.09338220150963733, 'max_depth': 7, 'n_estimators': 636, 'subsample': 0.7456910000806632, 'colsample_bytree': 0.7204154725481745, 'gamma': 7.163271428020571, 'min_child_weight': 8, 'scale_pos_weight': 18.927755481717814}. Best is trial 15 with value: 0.30952380952380953.

Best trial: 15. Best value: 0.309524:  58%|█████▊    | 29/50 [00:24<00:17,  1.23it/s]

[I 2025-12-07 15:21:18,934] Trial 28 finished with value: 0.2727272727272727 and parameters: {'learning_rate': 0.012299161278240822, 'max_depth': 8, 'n_estimators': 702, 'subsample': 0.8272680535197006, 'colsample_bytree': 0.8870808916086416, 'gamma': 2.9461860602891234, 'min_child_weight': 4, 'scale_pos_weight': 30.63018774874026}. Best is trial 15 with value: 0.30952380952380953.

Best trial: 15. Best value: 0.309524:  60%|██████    | 30/50 [00:26<00:20,  1.00s/it]

[I 2025-12-07 15:21:20,343] Trial 29 finished with value: 0.2911392405063291 and parameters: {'learning_rate': 0.12520979668864463, 'max_depth': 11, 'n_estimators': 476, 'subsample': 0.9714382627451744, 'colsample_bytree': 0.781578453520113, 'gamma': 1.7878316555861637, 'min_child_weight': 15, 'scale_pos_weight': 8.299263316480575}. Best is trial 15 with value: 0.30952380952380953.

Best trial: 15. Best value: 0.309524:  62%|██████▏   | 31/50 [00:28<00:23,  1.25s/it]

[I 2025-12-07 15:21:22,204] Trial 30 finished with value: 0.22727272727272727 and parameters: {'learning_rate': 0.054389918682528224, 'max_depth': 6, 'n_estimators': 552, 'subsample': 0.9229105405298841, 'colsample_bytree': 0.9088522031860257, 'gamma': 5.089583093722091, 'min_child_weight': 21, 'scale_pos_weight': 14.469203485265144}. Best is trial 15 with value: 0.30952380952380953.

Best trial: 15. Best value: 0.309524:  64%|██████▍   | 32/50 [00:29<00:23,  1.28s/it]

[I 2025-12-07 15:21:23,545] Trial 31 finished with value: 0.29133858267716534 and parameters: {'learning_rate': 0.09509555718890003, 'max_depth': 7, 'n_estimators': 626, 'subsample': 0.760821895131001, 'colsample_bytree': 0.7144941095690784, 'gamma': 7.129946699743421, 'min_child_weight': 8, 'scale_pos_weight': 20.441893437219957}. Best is trial 15 with value: 0.30952380952380953.

Best trial: 15. Best value: 0.309524:  66%|██████▌   | 33/50 [00:30<00:22,  1.29s/it]

[I 2025-12-07 15:21:24,889] Trial 32 finished with value: 0.2824427480916031 and parameters: {'learning_rate': 0.08563719704360843, 'max_depth': 9, 'n_estimators': 657, 'subsample': 0.7496602472348108, 'colsample_bytree': 0.722219246962251, 'gamma': 3.8266891947575132, 'min_child_weight': 11, 'scale_pos_weight': 25.09713498190246}. Best is trial 15 with value: 0.30952380952380953.

Best trial: 33. Best value: 0.311475:  68%|██████▊   | 34/50 [00:32<00:19,  1.24s/it]

[I 2025-12-07 15:21:25,995] Trial 33 finished with value: 0.3114754098360656 and parameters: {'learning_rate': 0.1143519365005338, 'max_depth': 7, 'n_estimators': 593, 'subsample': 0.6713457386962097, 'colsample_bytree': 0.7638810011813766, 'gamma': 7.1155557115650705, 'min_child_weight': 4, 'scale_pos_weight': 17.844719983435724}. Best is trial 33 with value: 0.3114754098360656.

Best trial: 33. Best value: 0.311475:  70%|███████   | 35/50 [00:34<00:22,  1.47s/it]

[I 2025-12-07 15:21:28,004] Trial 34 finished with value: 0.3025210084033613 and parameters: {'learning_rate': 0.11632953183414134, 'max_depth': 8, 'n_estimators': 589, 'subsample': 0.6538600305687949, 'colsample_bytree': 0.770412387778658, 'gamma': 5.639628455512984, 'min_child_weight': 4, 'scale_pos_weight': 16.4075268522039}. Best is trial 33 with value: 0.3114754098360656.

Best trial: 33. Best value: 0.311475:  72%|███████▏  | 36/50 [00:34<00:17,  1.22s/it]

[I 2025-12-07 15:21:28,659] Trial 35 finished with value: 0.2740740740740741 and parameters: {'learning_rate': 0.1573056650963925, 'max_depth': 5, 'n_estimators': 520, 'subsample': 0.7027285257877699, 'colsample_bytree': 0.8179171068406671, 'gamma': 7.8426364187089534, 'min_child_weight': 1, 'scale_pos_weight': 23.101052131393224}. Best is trial 33 with value: 0.3114754098360656.

Best trial: 33. Best value: 0.311475:  74%|███████▍  | 37/50 [00:35<00:14,  1.15s/it]

[I 2025-12-07 15:21:29,643] Trial 36 finished with value: 0.2835820895522388 and parameters: {'learning_rate': 0.18795020253042755, 'max_depth': 6, 'n_estimators': 685, 'subsample': 0.6372437654917293, 'colsample_bytree': 0.7681651195381151, 'gamma': 4.493644829879097, 'min_child_weight': 5, 'scale_pos_weight': 28.881219055948453}. Best is trial 33 with value: 0.3114754098360656.

Best trial: 33. Best value: 0.311475:  76%|███████▌  | 38/50 [00:35<00:10,  1.15it/s]

[I 2025-12-07 15:21:29,852] Trial 37 finished with value: 0.0 and parameters: {'learning_rate': 0.13795368024416357, 'max_depth': 7, 'n_estimators': 444, 'subsample': 0.8797520969527979, 'colsample_bytree': 0.8092287879196233, 'gamma': 3.4149111648770916, 'min_child_weight': 16, 'scale_pos_weight': 1.2831429654006605}. Best is trial 33 with value: 0.3114754098360656.

Best trial: 33. Best value: 0.311475:  78%|███████▊  | 39/50 [00:36<00:09,  1.12it/s]

[I 2025-12-07 15:21:30,813] Trial 38 finished with value: 0.2571428571428571 and parameters: {'learning_rate': 0.0446638117003232, 'max_depth': 9, 'n_estimators': 547, 'subsample': 0.6929587759794037, 'colsample_bytree': 0.7403625674504352, 'gamma': 2.515420540339406, 'min_child_weight': 12, 'scale_pos_weight': 32.96067191995575}. Best is trial 33 with value: 0.3114754098360656.

Best trial: 33. Best value: 0.311475:  80%|████████  | 40/50 [00:37<00:08,  1.24it/s]

[I 2025-12-07 15:21:31,404] Trial 39 finished with value: 0.27007299270072993 and parameters: {'learning_rate': 0.10836213329252743, 'max_depth': 8, 'n_estimators': 610, 'subsample': 0.7247192575612844, 'colsample_bytree': 0.8465881656520703, 'gamma': 9.767243500987357, 'min_child_weight': 9, 'scale_pos_weight': 24.890357776506963}. Best is trial 33 with value: 0.3114754098360656.

Best trial: 40. Best value: 0.318182:  82%|████████▏ | 41/50 [00:37<00:06,  1.39it/s]

[I 2025-12-07 15:21:31,915] Trial 40 finished with value: 0.3181818181818182 and parameters: {'learning_rate': 0.20629759924375413, 'max_depth': 10, 'n_estimators': 501, 'subsample': 0.6769317938111605, 'colsample_bytree': 0.7538357069661314, 'gamma': 6.121134174835306, 'min_child_weight': 2, 'scale_pos_weight': 12.925989455359213}. Best is trial 40 with value: 0.3181818181818182.

Best trial: 40. Best value: 0.318182:  84%|████████▍ | 42/50 [00:38<00:05,  1.49it/s]

[I 2025-12-07 15:21:32,476] Trial 41 finished with value: 0.3125 and parameters: {'learning_rate': 0.25222989428625503, 'max_depth': 10, 'n_estimators': 505, 'subsample': 0.6791814278278044, 'colsample_bytree': 0.7606727283836472, 'gamma': 5.952179878072475, 'min_child_weight': 2, 'scale_pos_weight': 12.4743597187421}. Best is trial 40 with value: 0.3181818181818182.

Best trial: 40. Best value: 0.318182:  86%|████████▌ | 43/50 [00:39<00:04,  1.56it/s]

[I 2025-12-07 15:21:33,049] Trial 42 finished with value: 0.2857142857142857 and parameters: {'learning_rate': 0.26385090361930014, 'max_depth': 10, 'n_estimators': 504, 'subsample': 0.6829565051446108, 'colsample_bytree': 0.7416495437485273, 'gamma': 6.057944082315645, 'min_child_weight': 2, 'scale_pos_weight': 12.176406011966757}. Best is trial 40 with value: 0.3181818181818182.

Best trial: 43. Best value: 0.32:  88%|████████▊ | 44/50 [00:39<00:03,  1.71it/s]

[I 2025-12-07 15:21:33,506] Trial 43 finished with value: 0.32 and parameters: {'learning_rate': 0.20689354249859038, 'max_depth': 11, 'n_estimators': 491, 'subsample': 0.6314482426788469, 'colsample_bytree': 0.7611537779477471, 'gamma': 7.459337358213408, 'min_child_weight': 4, 'scale_pos_weight': 6.463444949136939}. Best is trial 43 with value: 0.32.

Best trial: 43. Best value: 0.32:  90%|█████████ | 45/50 [00:39<00:02,  1.97it/s]

[I 2025-12-07 15:21:33,831] Trial 44 finished with value: 0.27672955974842767 and parameters: {'learning_rate': 0.20850724640144114, 'max_depth': 12, 'n_estimators': 365, 'subsample': 0.6305997033126005, 'colsample_bytree': 0.7665240841964202, 'gamma': 8.342839939830258, 'min_child_weight': 4, 'scale_pos_weight': 8.022844414874037}. Best is trial 43 with value: 0.32.

Best trial: 43. Best value: 0.32:  92%|█████████▏| 46/50 [00:40<00:01,  2.07it/s]

[I 2025-12-07 15:21:34,262] Trial 45 finished with value: 0.16666666666666666 and parameters: {'learning_rate': 0.24163830443107168, 'max_depth': 11, 'n_estimators': 496, 'subsample': 0.6768317750985382, 'colsample_bytree': 0.6337654256208294, 'gamma': 7.19038678424538, 'min_child_weight': 20, 'scale_pos_weight': 5.252943539051148}. Best is trial 43 with value: 0.32.

Best trial: 46. Best value: 0.328947:  94%|█████████▍| 47/50 [00:40<00:01,  2.25it/s]

[I 2025-12-07 15:21:34,609] Trial 46 finished with value: 0.32894736842105265 and parameters: {'learning_rate': 0.21844037088223772, 'max_depth': 10, 'n_estimators': 428, 'subsample': 0.6328190134866417, 'colsample_bytree': 0.683076418435748, 'gamma': 6.795441648601808, 'min_child_weight': 2, 'scale_pos_weight': 6.107396738658709}. Best is trial 46 with value: 0.32894736842105265.

Best trial: 46. Best value: 0.328947:  96%|█████████▌| 48/50 [00:41<00:00,  2.38it/s]

[I 2025-12-07 15:21:34,977] Trial 47 finished with value: 0.32432432432432434 and parameters: {'learning_rate': 0.22335029642037874, 'max_depth': 10, 'n_estimators': 438, 'subsample': 0.6299192178027494, 'colsample_bytree': 0.6786114681684803, 'gamma': 5.486835309607679, 'min_child_weight': 2, 'scale_pos_weight': 5.137841454458313}. Best is trial 46 with value: 0.32894736842105265.

Best trial: 46. Best value: 0.328947:  98%|█████████▊| 49/50 [00:41<00:00,  2.57it/s]

[I 2025-12-07 15:21:35,293] Trial 48 finished with value: 0.176 and parameters: {'learning_rate': 0.22137497991097638, 'max_depth': 11, 'n_estimators': 443, 'subsample': 0.6343510630997351, 'colsample_bytree': 0.6608043224990365, 'gamma': 7.623773120886611, 'min_child_weight': 2, 'scale_pos_weight': 5.1606293507735925}. Best is trial 46 with value: 0.32894736842105265.

Best trial: 46. Best value: 0.328947: 100%|██████████| 50/50 [00:41<00:00,  1.20it/s]

[I 2025-12-07 15:21:35,515] Trial 49 finished with value: 0.0 and parameters: {'learning_rate': 0.26792934246653993, 'max_depth': 10, 'n_estimators': 435, 'subsample': 0.6193995786142743, 'colsample_bytree': 0.6781224478758816, 'gamma': 5.47501416292495, 'min_child_weight': 2, 'scale_pos_weight': 1.2524296125602135}. Best is trial 46 with value: 0.32894736842105265.

In [26]:
best_params = study_xgb.best_params

final_xgb = XGBClassifier(
    **best_params,
    random_state=42,
    n_jobs=-1,
    eval_metric="logloss",
    tree_method="hist"
)

final_xgb.fit(X_train, y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=0.683076418435748, device=None,
              early_stopping_rounds=None, enable_categorical=False,
              eval_metric='logloss', feature_types=None, feature_weights=None,
              gamma=6.795441648601808, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=0.21844037088223772,
              max_bin=None, max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=10, max_leaves=None,
              min_child_weight=2, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=428, n_jobs=-1,
              num_parallel_tree=None, ...)

In [27]:
y_pred_test = final_xgb.predict(X_test)
print(classification_report(y_test, y_pred_test))

              precision    recall  f1-score   support

           0       0.99      0.99      0.99      5376
           1       0.23      0.19      0.21        93

    accuracy                           0.98      5469
   macro avg       0.61      0.59      0.60      5469
weighted avg       0.97      0.98      0.97      5469

In [28]:
probs = final_xgb.predict_proba(X_test)[:, 1]

In [29]:
thresholds = np.linspace(0.01, 0.99, 200)

results = []

best_threshold = 0
best_f1 = 0

for t in thresholds:
    preds = (probs >= t).astype(int)
    f1 = f1_score(y_test, preds)
    precision = precision_score(y_test, preds, zero_division=0)
    recall = recall_score(y_test, preds)

    results.append([t, precision, recall, f1])

    if f1 > best_f1:
        best_f1 = f1
        best_threshold = t

print(f"Best threshold: {best_threshold:.3f}")
print(f"Best F1 score: {best_f1:.4f}")

Best threshold: 0.360
Best F1 score: 0.2783

In [30]:
final_preds = (probs >= best_threshold).astype(int)

from sklearn.metrics import classification_report
print(classification_report(y_test, final_preds))

              precision    recall  f1-score   support

           0       0.99      0.98      0.98      5376
           1       0.23      0.34      0.28        93

    accuracy                           0.97      5469
   macro avg       0.61      0.66      0.63      5469
weighted avg       0.98      0.97      0.97      5469

# CATBOOST

In [31]:
path_to_repo = Path('..').resolve()
path_to_data = path_to_repo / 'data'

df_cat = pd.read_csv(path_to_data / 'data_catboost.csv')
df_cat.head()

,ID,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,NAME_INCOME_TYPE,NAME_EDUCATION_TYPE,NAME_FAMILY_STATUS,NAME_HOUSING_TYPE,FLAG_MOBIL,FLAG_WORK_PHONE,FLAG_PHONE,FLAG_EMAIL,OCCUPATION_TYPE,CNT_FAM_MEMBERS,AGE,EXPERIENCE,bad
0,5008804,M,Y,Y,0,427500.0,Working,Higher education,Civil marriage,Rented apartment,1,1,0,0,NaN,2.0,32,12,0
1,5008805,M,Y,Y,0,427500.0,Working,Higher education,Civil marriage,Rented apartment,1,1,0,0,NaN,2.0,32,12,0
2,5008806,M,Y,Y,0,112500.0,Working,Secondary / secondary special,Married,House / apartment,1,0,0,0,Security staff,2.0,58,3,0
3,5008808,F,N,Y,0,270000.0,Commercial associate,Secondary / secondary special,Single / not married,House / apartment,1,0,1,1,Sales staff,1.0,52,8,0
4,5008809,F,N,Y,0,270000.0,Commercial associate,Secondary / secondary special,Single / not married,House / apartment,1,0,1,1,Sales staff,1.0,52,8,0

In [ ]:
y = df_cat["bad"]
X = df_cat.drop(columns=["bad", "ID"])

In [ ]:
cat_features = X.select_dtypes(include=["object"]).columns.tolist()
print(cat_features)

['CODE_GENDER', 'FLAG_OWN_CAR', 'FLAG_OWN_REALTY', 'NAME_INCOME_TYPE', 'NAME_EDUCATION_TYPE', 'NAME_FAMILY_STATUS', 'NAME_HOUSING_TYPE', 'OCCUPATION_TYPE']

In [ ]:
for col in cat_features:
    X[col] = X[col].fillna("missing").astype(str)

In [ ]:
cat_idx = [X.columns.get_loc(c) for c in cat_features]

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

In [37]:
train_pool = Pool(X_train, y_train, cat_features=cat_idx)
test_pool  = Pool(X_test,  y_test,  cat_features=cat_idx)

In [38]:
model_cb = CatBoostClassifier(
    loss_function="Logloss",
    eval_metric="AUC",
    iterations=1500,
    learning_rate=0.03,
    depth=8,
    l2_leaf_reg=5,
    random_seed=42,
    border_count=128,
    auto_class_weights='Balanced',  
    verbose=200
)

In [39]:
%time model_cb.fit(train_pool, eval_set=test_pool)

0:	test: 0.4948695	best: 0.4948695 (0)	total: 75.1ms	remaining: 1m 52s
200:	test: 0.6444311	best: 0.6447997 (168)	total: 5.13s	remaining: 33.2s
400:	test: 0.6932938	best: 0.6932938 (400)	total: 8.34s	remaining: 22.9s
600:	test: 0.7064251	best: 0.7077588 (489)	total: 14.7s	remaining: 22.1s
800:	test: 0.7077985	best: 0.7083315 (770)	total: 18.5s	remaining: 16.1s
1000:	test: 0.7070001	best: 0.7083315 (770)	total: 21.8s	remaining: 10.9s
1200:	test: 0.7102707	best: 0.7106835 (1160)	total: 25s	remaining: 6.22s
1400:	test: 0.7113492	best: 0.7115284 (1395)	total: 28.3s	remaining: 2s
1499:	test: 0.7117564	best: 0.7126545 (1483)	total: 29.9s	remaining: 0us

bestTest = 0.7126545299
bestIteration = 1483

Shrink model to first 1484 iterations.
CPU times: user 2min 22s, sys: 17.6 s, total: 2min 39s
Wall time: 30.2 s

In [40]:
probs = model_cb.predict_proba(test_pool)[:, 1]
preds_default = (probs >= 0.5).astype(int)

In [41]:
print(classification_report(y_test, preds_default))

              precision    recall  f1-score   support

           0       0.99      0.96      0.98      7169
           1       0.16      0.44      0.24       123

    accuracy                           0.95      7292
   macro avg       0.58      0.70      0.61      7292
weighted avg       0.98      0.95      0.96      7292

## Catboost + threshold tuning

In [42]:
thresholds = np.linspace(0.1, 0.9, 200)
best_t = 0.5
best_f1 = 0

for t in thresholds:
    preds_t = (probs >= t).astype(int)
    f1 = f1_score(y_test, preds_t)
    if f1 > best_f1:
        best_f1 = f1
        best_t = t

In [43]:
final_preds = (probs >= best_t).astype(int)
print(classification_report(y_test, final_preds))

              precision    recall  f1-score   support

           0       0.99      0.97      0.98      7169
           1       0.20      0.40      0.26       123

    accuracy                           0.96      7292
   macro avg       0.59      0.69      0.62      7292
weighted avg       0.98      0.96      0.97      7292

# LIGHTGBM CLASSIFIER

In [44]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

In [59]:
lgbm_model = LGBMClassifier(
    n_estimators=200,
    learning_rate=0.05,
    num_leaves=31,          
    is_unbalance=True,    
    random_state=42,
    n_jobs=-1,        
    importance_type='gain',  
    verbose=-1              
)

In [60]:
if 'ID' in df.columns: df = df.drop('ID', axis=1)
cat_cols = df.select_dtypes(include=['object']).columns
for col in cat_cols: df[col] = df[col].astype('category')

X = df.drop('bad', axis=1)
y = df['bad']

In [61]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

In [62]:
lgbm_model.fit(X_train, y_train, eval_set=[(X_test, y_test)])
probs = lgbm_model.predict_proba(X_test)[:, 1]

In [63]:
print(classification_report(y_test, lgbm_model.predict(X_test)))

              precision    recall  f1-score   support

           0       0.99      0.91      0.95      7169
           1       0.08      0.46      0.14       123

    accuracy                           0.90      7292
   macro avg       0.53      0.69      0.54      7292
weighted avg       0.97      0.90      0.93      7292

In [64]:
feature_importance = pd.DataFrame({'feature': X.columns,'importance': lgbm_model.feature_importances_}).sort_values('importance', ascending=False)
feature_importance.head(20)

                feature     importance
15           LOG_INCOME  129173.562169
13                  AGE  127562.952875
14           EXPERIENCE   93681.896914
6    NAME_FAMILY_STATUS   28058.561237
4      NAME_INCOME_TYPE   26847.776467
12      CNT_FAM_MEMBERS   19129.876660
5   NAME_EDUCATION_TYPE   18380.298199
1          FLAG_OWN_CAR   17775.111566
3          CNT_CHILDREN   14980.912199
2       FLAG_OWN_REALTY   14840.206510
7     NAME_HOUSING_TYPE   11207.125672
9       FLAG_WORK_PHONE   10406.545392
10           FLAG_PHONE    9866.724299
0           CODE_GENDER    7379.815957
11           FLAG_EMAIL    6815.957033
8            FLAG_MOBIL       0.000000

## LIGHTGBM + Threshold Tuning

In [65]:
thresholds = np.linspace(0.1, 0.9, 100)
best_threshold = 0.5
best_f1 = 0.0

In [66]:
for thresh in thresholds:
    y_pred_custom = (probs >= thresh).astype(int)
    score = f1_score(y_test, y_pred_custom)
    
    if score > best_f1:
        best_f1 = score
        best_threshold = thresh

In [67]:
final_preds = (probs >= best_threshold).astype(int)
print(classification_report(y_test, final_preds))

              precision    recall  f1-score   support

           0       0.99      0.98      0.98      7169
           1       0.18      0.30      0.22       123

    accuracy                           0.97      7292
   macro avg       0.58      0.64      0.60      7292
weighted avg       0.97      0.97      0.97      7292

In [68]:
df2 = df.copy()

if 'ID' in df2.columns:
    df2 = df2.drop('ID', axis=1)

for col in df2.select_dtypes(include=['object']).columns:
    df2[col] = df2[col].astype('category')

X = df2.drop('bad', axis=1)
y = df2['bad']

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

# LIGHTGBM + Hyperparameter Tuning

In [69]:
def objective(trial):
    params = {
        "n_estimators": trial.suggest_int("n_estimators", 100, 800),
        "learning_rate": trial.suggest_float("learning_rate", 0.01, 0.2),
        "num_leaves": trial.suggest_int("num_leaves", 20, 80),
        "max_depth": trial.suggest_int("max_depth", 3, 12),
        "min_child_samples": trial.suggest_int("min_child_samples", 5, 80),
        "subsample": trial.suggest_float("subsample", 0.6, 1.0),
        "colsample_bytree": trial.suggest_float("colsample_bytree", 0.6, 1.0),
        "reg_alpha": trial.suggest_float("reg_alpha", 1e-3, 10.0, log=True),
        "reg_lambda": trial.suggest_float("reg_lambda", 1e-3, 10.0, log=True),
    }

    model = LGBMClassifier(
        random_state=42,
        n_jobs=-1,
        **params
    )

    model.fit(X_train, y_train)

    y_pred_val = model.predict(X_val)

    return f1_score(y_val, y_pred_val)

In [70]:
study = optuna.create_study(direction="maximize")
study.optimize(objective, n_trials=50, show_progress_bar=True)

[I 2025-12-07 15:28:52,032] A new study created in memory with name: no-name-696991b2-b838-4e7f-b317-d51e6162b4c4
Best trial: 0. Best value: 0.150943:   2%|▏         | 1/50 [00:00<00:48,  1.02it/s]

[I 2025-12-07 15:28:53,023] Trial 0 finished with value: 0.1509433962264151 and parameters: {'n_estimators': 594, 'learning_rate': 0.07903633771638861, 'num_leaves': 42, 'max_depth': 4, 'min_child_samples': 32, 'subsample': 0.6128548235754012, 'colsample_bytree': 0.7013949539615364, 'reg_alpha': 0.19607825312892052, 'reg_lambda': 0.17517782468774443}. Best is trial 0 with value: 0.1509433962264151.

Best trial: 1. Best value: 0.206897:   4%|▍         | 2/50 [00:02<01:07,  1.40s/it]

[I 2025-12-07 15:28:54,718] Trial 1 finished with value: 0.20689655172413793 and parameters: {'n_estimators': 275, 'learning_rate': 0.06148220930327306, 'num_leaves': 49, 'max_depth': 11, 'min_child_samples': 42, 'subsample': 0.8261904810345557, 'colsample_bytree': 0.727201901243136, 'reg_alpha': 0.35018182535509745, 'reg_lambda': 0.0712320190377407}. Best is trial 1 with value: 0.20689655172413793.

Best trial: 2. Best value: 0.378788:   6%|▌         | 3/50 [00:04<01:25,  1.81s/it]

[I 2025-12-07 15:28:57,018] Trial 2 finished with value: 0.3787878787878788 and parameters: {'n_estimators': 435, 'learning_rate': 0.13436890573623989, 'num_leaves': 55, 'max_depth': 7, 'min_child_samples': 34, 'subsample': 0.7253406873070433, 'colsample_bytree': 0.689734158353284, 'reg_alpha': 0.006938074232243467, 'reg_lambda': 0.001363058197522185}. Best is trial 2 with value: 0.3787878787878788.

Best trial: 2. Best value: 0.378788:   8%|▊         | 4/50 [00:05<00:59,  1.29s/it]

[I 2025-12-07 15:28:57,507] Trial 3 finished with value: 0.0425531914893617 and parameters: {'n_estimators': 479, 'learning_rate': 0.08715740688360245, 'num_leaves': 32, 'max_depth': 3, 'min_child_samples': 36, 'subsample': 0.8390093581366006, 'colsample_bytree': 0.8710893388208256, 'reg_alpha': 0.9815380001144713, 'reg_lambda': 1.1371274752013754}. Best is trial 2 with value: 0.3787878787878788.

Best trial: 2. Best value: 0.378788:  10%|█         | 5/50 [00:06<00:49,  1.09s/it]

[I 2025-12-07 15:28:58,257] Trial 4 finished with value: 0.2833333333333333 and parameters: {'n_estimators': 116, 'learning_rate': 0.13207045351161487, 'num_leaves': 53, 'max_depth': 11, 'min_child_samples': 62, 'subsample': 0.6374104453224376, 'colsample_bytree': 0.9824959193717575, 'reg_alpha': 0.03120712130884277, 'reg_lambda': 0.004924156942746452}. Best is trial 2 with value: 0.3787878787878788.

Best trial: 2. Best value: 0.378788:  12%|█▏        | 6/50 [00:07<00:51,  1.16s/it]

[I 2025-12-07 15:28:59,554] Trial 5 finished with value: 0.08247422680412371 and parameters: {'n_estimators': 771, 'learning_rate': 0.07845532025636616, 'num_leaves': 57, 'max_depth': 4, 'min_child_samples': 14, 'subsample': 0.9793212707144946, 'colsample_bytree': 0.6110044484370347, 'reg_alpha': 0.0038681793841329115, 'reg_lambda': 3.7412561668200364}. Best is trial 2 with value: 0.3787878787878788.

Best trial: 2. Best value: 0.378788:  14%|█▍        | 7/50 [00:08<00:46,  1.09s/it]

[I 2025-12-07 15:29:00,486] Trial 6 finished with value: 0.0625 and parameters: {'n_estimators': 595, 'learning_rate': 0.051290184280033846, 'num_leaves': 27, 'max_depth': 4, 'min_child_samples': 56, 'subsample': 0.7581916990268457, 'colsample_bytree': 0.9682480603009277, 'reg_alpha': 0.011302400269863419, 'reg_lambda': 0.00198232035234753}. Best is trial 2 with value: 0.3787878787878788.

Best trial: 2. Best value: 0.378788:  16%|█▌        | 8/50 [00:09<00:39,  1.07it/s]

[I 2025-12-07 15:29:01,100] Trial 7 finished with value: 0.17475728155339806 and parameters: {'n_estimators': 611, 'learning_rate': 0.13960639472347602, 'num_leaves': 25, 'max_depth': 3, 'min_child_samples': 24, 'subsample': 0.9480464970450695, 'colsample_bytree': 0.8895449019383578, 'reg_alpha': 0.10200088853602393, 'reg_lambda': 0.21599899303415415}. Best is trial 2 with value: 0.3787878787878788.

Best trial: 2. Best value: 0.378788:  18%|█▊        | 9/50 [00:12<01:06,  1.63s/it]

[I 2025-12-07 15:29:04,259] Trial 8 finished with value: 0.33070866141732286 and parameters: {'n_estimators': 560, 'learning_rate': 0.17009447962254032, 'num_leaves': 62, 'max_depth': 7, 'min_child_samples': 78, 'subsample': 0.7801067691208506, 'colsample_bytree': 0.6255519368236353, 'reg_alpha': 0.2071159833943756, 'reg_lambda': 1.0104214671874319}. Best is trial 2 with value: 0.3787878787878788.

Best trial: 2. Best value: 0.378788:  20%|██        | 10/50 [00:13<00:58,  1.47s/it]

[I 2025-12-07 15:29:05,372] Trial 9 finished with value: 0.1509433962264151 and parameters: {'n_estimators': 655, 'learning_rate': 0.07766525660807375, 'num_leaves': 23, 'max_depth': 4, 'min_child_samples': 46, 'subsample': 0.7109751277550694, 'colsample_bytree': 0.869439439531444, 'reg_alpha': 0.005687570211818553, 'reg_lambda': 0.009478655076991386}. Best is trial 2 with value: 0.3787878787878788.

Best trial: 2. Best value: 0.378788:  22%|██▏       | 11/50 [00:15<01:08,  1.76s/it]

[I 2025-12-07 15:29:07,784] Trial 10 finished with value: 0.06 and parameters: {'n_estimators': 350, 'learning_rate': 0.01386498283545598, 'num_leaves': 79, 'max_depth': 8, 'min_child_samples': 11, 'subsample': 0.8956879767857585, 'colsample_bytree': 0.7633255936932335, 'reg_alpha': 0.0010989853673039522, 'reg_lambda': 0.0010474809388762963}. Best is trial 2 with value: 0.3787878787878788.

Best trial: 2. Best value: 0.378788:  24%|██▍       | 12/50 [00:16<00:51,  1.36s/it]

[I 2025-12-07 15:29:08,225] Trial 11 finished with value: 0.0 and parameters: {'n_estimators': 441, 'learning_rate': 0.19668316437557054, 'num_leaves': 68, 'max_depth': 7, 'min_child_samples': 76, 'subsample': 0.713491390033102, 'colsample_bytree': 0.6007458545468445, 'reg_alpha': 5.4413215381921205, 'reg_lambda': 1.2564666183857516}. Best is trial 2 with value: 0.3787878787878788.

Best trial: 2. Best value: 0.378788:  26%|██▌       | 13/50 [00:18<01:02,  1.70s/it]

[I 2025-12-07 15:29:10,695] Trial 12 finished with value: 0.366412213740458 and parameters: {'n_estimators': 458, 'learning_rate': 0.17304742713736035, 'num_leaves': 65, 'max_depth': 7, 'min_child_samples': 79, 'subsample': 0.775165693457676, 'colsample_bytree': 0.6732039769379505, 'reg_alpha': 0.03642586653784755, 'reg_lambda': 0.02633477118232683}. Best is trial 2 with value: 0.3787878787878788.

Best trial: 2. Best value: 0.378788:  28%|██▊       | 14/50 [00:21<01:08,  1.91s/it]

[I 2025-12-07 15:29:13,114] Trial 13 finished with value: 0.366412213740458 and parameters: {'n_estimators': 314, 'learning_rate': 0.13227634735067312, 'num_leaves': 71, 'max_depth': 9, 'min_child_samples': 61, 'subsample': 0.6913648127645438, 'colsample_bytree': 0.6842673774158078, 'reg_alpha': 0.025354525066104246, 'reg_lambda': 0.026772761347262735}. Best is trial 2 with value: 0.3787878787878788.

Best trial: 2. Best value: 0.378788:  30%|███       | 15/50 [00:22<01:05,  1.87s/it]

[I 2025-12-07 15:29:14,883] Trial 14 finished with value: 0.35658914728682173 and parameters: {'n_estimators': 424, 'learning_rate': 0.16131623192990238, 'num_leaves': 43, 'max_depth': 6, 'min_child_samples': 23, 'subsample': 0.8741483733343937, 'colsample_bytree': 0.7908107571589231, 'reg_alpha': 0.04423195863917312, 'reg_lambda': 0.018688677159022563}. Best is trial 2 with value: 0.3787878787878788.

Best trial: 2. Best value: 0.378788:  32%|███▏      | 16/50 [00:24<00:57,  1.69s/it]

[I 2025-12-07 15:29:16,150] Trial 15 finished with value: 0.3384615384615385 and parameters: {'n_estimators': 170, 'learning_rate': 0.19039419004606978, 'num_leaves': 63, 'max_depth': 9, 'min_child_samples': 52, 'subsample': 0.7621618297834253, 'colsample_bytree': 0.678173012562348, 'reg_alpha': 0.0028642297051069267, 'reg_lambda': 0.0034552452540801103}. Best is trial 2 with value: 0.3787878787878788.

Best trial: 2. Best value: 0.378788:  34%|███▍      | 17/50 [00:25<00:57,  1.74s/it]

[I 2025-12-07 15:29:18,004] Trial 16 finished with value: 0.33070866141732286 and parameters: {'n_estimators': 240, 'learning_rate': 0.11268203457847817, 'num_leaves': 79, 'max_depth': 9, 'min_child_samples': 66, 'subsample': 0.660778612471093, 'colsample_bytree': 0.658985487069775, 'reg_alpha': 0.012794937018458812, 'reg_lambda': 0.045290282519110096}. Best is trial 2 with value: 0.3787878787878788.

Best trial: 2. Best value: 0.378788:  36%|███▌      | 18/50 [00:26<00:48,  1.51s/it]

[I 2025-12-07 15:29:18,999] Trial 17 finished with value: 0.16363636363636364 and parameters: {'n_estimators': 401, 'learning_rate': 0.1602796729477733, 'num_leaves': 47, 'max_depth': 6, 'min_child_samples': 71, 'subsample': 0.7373956368783223, 'colsample_bytree': 0.735788045017299, 'reg_alpha': 1.1111025496091922, 'reg_lambda': 0.009375696540428555}. Best is trial 2 with value: 0.3787878787878788.

Best trial: 2. Best value: 0.378788:  38%|███▊      | 19/50 [00:28<00:50,  1.62s/it]

[I 2025-12-07 15:29:20,852] Trial 18 finished with value: 0.3464566929133858 and parameters: {'n_estimators': 517, 'learning_rate': 0.10819529456938308, 'num_leaves': 70, 'max_depth': 6, 'min_child_samples': 25, 'subsample': 0.7878200744977456, 'colsample_bytree': 0.7955227249224098, 'reg_alpha': 0.0011157627050506788, 'reg_lambda': 0.0010445191431592818}. Best is trial 2 with value: 0.3787878787878788.

Best trial: 19. Best value: 0.4:  40%|████      | 20/50 [00:31<01:02,  2.08s/it]

[I 2025-12-07 15:29:24,011] Trial 19 finished with value: 0.4 and parameters: {'n_estimators': 720, 'learning_rate': 0.17871708997260422, 'num_leaves': 37, 'max_depth': 8, 'min_child_samples': 46, 'subsample': 0.8138128591371155, 'colsample_bytree': 0.8345182749963902, 'reg_alpha': 0.07906774884736209, 'reg_lambda': 0.4171411136018114}. Best is trial 19 with value: 0.4.

Best trial: 19. Best value: 0.4:  42%|████▏     | 21/50 [00:35<01:09,  2.40s/it]

[I 2025-12-07 15:29:27,145] Trial 20 finished with value: 0.25210084033613445 and parameters: {'n_estimators': 711, 'learning_rate': 0.14680318798751896, 'num_leaves': 34, 'max_depth': 10, 'min_child_samples': 46, 'subsample': 0.8988634205889636, 'colsample_bytree': 0.8447683119813177, 'reg_alpha': 0.07766813703535588, 'reg_lambda': 9.813450391671045}. Best is trial 19 with value: 0.4.

Best trial: 21. Best value: 0.402985:  44%|████▍     | 22/50 [00:39<01:22,  2.95s/it]

[I 2025-12-07 15:29:31,383] Trial 21 finished with value: 0.40298507462686567 and parameters: {'n_estimators': 686, 'learning_rate': 0.1791226515409261, 'num_leaves': 57, 'max_depth': 8, 'min_child_samples': 34, 'subsample': 0.8144664604824144, 'colsample_bytree': 0.8318323204244564, 'reg_alpha': 0.01300735448642659, 'reg_lambda': 0.2677900800295601}. Best is trial 21 with value: 0.40298507462686567.

Best trial: 21. Best value: 0.402985:  46%|████▌     | 23/50 [00:44<01:38,  3.65s/it]

[I 2025-12-07 15:29:36,658] Trial 22 finished with value: 0.40298507462686567 and parameters: {'n_estimators': 782, 'learning_rate': 0.1775615200621653, 'num_leaves': 57, 'max_depth': 9, 'min_child_samples': 34, 'subsample': 0.8383410303639862, 'colsample_bytree': 0.9319229985088063, 'reg_alpha': 0.011243942958391916, 'reg_lambda': 0.2770367221866763}. Best is trial 21 with value: 0.40298507462686567.

Best trial: 21. Best value: 0.402985:  48%|████▊     | 24/50 [00:48<01:38,  3.79s/it]

[I 2025-12-07 15:29:40,798] Trial 23 finished with value: 0.39097744360902253 and parameters: {'n_estimators': 797, 'learning_rate': 0.1835002630408281, 'num_leaves': 38, 'max_depth': 8, 'min_child_samples': 40, 'subsample': 0.8271169596912179, 'colsample_bytree': 0.9283433885004734, 'reg_alpha': 0.015703224708418173, 'reg_lambda': 0.37316007196641954}. Best is trial 21 with value: 0.40298507462686567.

Best trial: 21. Best value: 0.402985:  50%|█████     | 25/50 [00:53<01:44,  4.18s/it]

[I 2025-12-07 15:29:45,877] Trial 24 finished with value: 0.39097744360902253 and parameters: {'n_estimators': 706, 'learning_rate': 0.1803336990103462, 'num_leaves': 58, 'max_depth': 12, 'min_child_samples': 28, 'subsample': 0.8641446535795559, 'colsample_bytree': 0.9231761837063108, 'reg_alpha': 0.07516989970368186, 'reg_lambda': 0.5824875325973112}. Best is trial 21 with value: 0.40298507462686567.

Best trial: 21. Best value: 0.402985:  52%|█████▏    | 26/50 [00:57<01:39,  4.14s/it]

[I 2025-12-07 15:29:49,932] Trial 25 finished with value: 0.4 and parameters: {'n_estimators': 737, 'learning_rate': 0.19911792500102288, 'num_leaves': 45, 'max_depth': 10, 'min_child_samples': 5, 'subsample': 0.930650199489241, 'colsample_bytree': 0.8298629602711228, 'reg_alpha': 0.017914976565421827, 'reg_lambda': 0.1340262162191954}. Best is trial 21 with value: 0.40298507462686567.

Best trial: 21. Best value: 0.402985:  54%|█████▍    | 27/50 [01:01<01:31,  3.98s/it]

[I 2025-12-07 15:29:53,534] Trial 26 finished with value: 0.39097744360902253 and parameters: {'n_estimators': 661, 'learning_rate': 0.15595065137653755, 'num_leaves': 51, 'max_depth': 8, 'min_child_samples': 50, 'subsample': 0.8474023678452972, 'colsample_bytree': 0.9230856886628139, 'reg_alpha': 0.002402509041185467, 'reg_lambda': 0.42334929946241695}. Best is trial 21 with value: 0.40298507462686567.

Best trial: 21. Best value: 0.402985:  56%|█████▌    | 28/50 [01:04<01:22,  3.73s/it]

[I 2025-12-07 15:29:56,693] Trial 27 finished with value: 0.2764227642276423 and parameters: {'n_estimators': 663, 'learning_rate': 0.11885847825114515, 'num_leaves': 37, 'max_depth': 10, 'min_child_samples': 18, 'subsample': 0.8090095221745223, 'colsample_bytree': 0.8324188039508348, 'reg_alpha': 0.00712416744906804, 'reg_lambda': 2.7080718837193434}. Best is trial 21 with value: 0.40298507462686567.

Best trial: 21. Best value: 0.402985:  58%|█████▊    | 29/50 [01:07<01:15,  3.61s/it]

[I 2025-12-07 15:30:00,004] Trial 28 finished with value: 0.3787878787878788 and parameters: {'n_estimators': 800, 'learning_rate': 0.14897012325318454, 'num_leaves': 59, 'max_depth': 9, 'min_child_samples': 38, 'subsample': 0.8000335482272666, 'colsample_bytree': 0.9576786708844148, 'reg_alpha': 0.1885735361335166, 'reg_lambda': 0.07673777783408359}. Best is trial 21 with value: 0.40298507462686567.

Best trial: 21. Best value: 0.402985:  60%|██████    | 30/50 [01:09<01:00,  3.04s/it]

[I 2025-12-07 15:30:01,726] Trial 29 finished with value: 0.2786885245901639 and parameters: {'n_estimators': 749, 'learning_rate': 0.17051599104925416, 'num_leaves': 40, 'max_depth': 5, 'min_child_samples': 32, 'subsample': 0.9022061915620421, 'colsample_bytree': 0.8918041221353114, 'reg_alpha': 0.4390240609466503, 'reg_lambda': 0.23427401668768702}. Best is trial 21 with value: 0.40298507462686567.

Best trial: 21. Best value: 0.402985:  62%|██████▏   | 31/50 [01:14<01:09,  3.67s/it]

[I 2025-12-07 15:30:06,877] Trial 30 finished with value: 0.39097744360902253 and parameters: {'n_estimators': 706, 'learning_rate': 0.17993814939055336, 'num_leaves': 74, 'max_depth': 8, 'min_child_samples': 30, 'subsample': 0.605185319688777, 'colsample_bytree': 0.7741241676147143, 'reg_alpha': 0.056503267770935894, 'reg_lambda': 0.15319956856529887}. Best is trial 21 with value: 0.40298507462686567.

Best trial: 21. Best value: 0.402985:  64%|██████▍   | 32/50 [01:19<01:09,  3.87s/it]

[I 2025-12-07 15:30:11,199] Trial 31 finished with value: 0.40298507462686567 and parameters: {'n_estimators': 738, 'learning_rate': 0.1924345101217113, 'num_leaves': 48, 'max_depth': 10, 'min_child_samples': 9, 'subsample': 0.9339941035895756, 'colsample_bytree': 0.8269836573236636, 'reg_alpha': 0.020816797174129473, 'reg_lambda': 0.1274902915094852}. Best is trial 21 with value: 0.40298507462686567.

Best trial: 21. Best value: 0.402985:  66%|██████▌   | 33/50 [01:23<01:07,  3.95s/it]

[I 2025-12-07 15:30:15,340] Trial 32 finished with value: 0.39097744360902253 and parameters: {'n_estimators': 641, 'learning_rate': 0.18816105509899675, 'num_leaves': 50, 'max_depth': 11, 'min_child_samples': 19, 'subsample': 0.9948739083837611, 'colsample_bytree': 0.8098874012434955, 'reg_alpha': 0.1263833282394483, 'reg_lambda': 0.5651049544056518}. Best is trial 21 with value: 0.40298507462686567.

Best trial: 21. Best value: 0.402985:  68%|██████▊   | 34/50 [01:26<00:59,  3.72s/it]

[I 2025-12-07 15:30:18,528] Trial 33 finished with value: 0.40298507462686567 and parameters: {'n_estimators': 546, 'learning_rate': 0.19866370338050335, 'num_leaves': 47, 'max_depth': 10, 'min_child_samples': 44, 'subsample': 0.928570311074539, 'colsample_bytree': 0.7375871924121591, 'reg_alpha': 0.009342704349114975, 'reg_lambda': 0.05477608760706966}. Best is trial 21 with value: 0.40298507462686567.

Best trial: 21. Best value: 0.402985:  70%|███████   | 35/50 [01:30<00:55,  3.72s/it]

[I 2025-12-07 15:30:22,234] Trial 34 finished with value: 0.40298507462686567 and parameters: {'n_estimators': 548, 'learning_rate': 0.1964049242019048, 'num_leaves': 54, 'max_depth': 12, 'min_child_samples': 35, 'subsample': 0.9424088965827356, 'colsample_bytree': 0.7243472778226644, 'reg_alpha': 0.008754556662690904, 'reg_lambda': 0.05930358191206793}. Best is trial 21 with value: 0.40298507462686567.

Best trial: 21. Best value: 0.402985:  72%|███████▏  | 36/50 [01:33<00:51,  3.66s/it]

[I 2025-12-07 15:30:25,769] Trial 35 finished with value: 0.39097744360902253 and parameters: {'n_estimators': 623, 'learning_rate': 0.1661153385573922, 'num_leaves': 47, 'max_depth': 10, 'min_child_samples': 5, 'subsample': 0.9592388749886844, 'colsample_bytree': 0.7523343426897877, 'reg_alpha': 0.0046211785927667975, 'reg_lambda': 0.11690809450623672}. Best is trial 21 with value: 0.40298507462686567.

Best trial: 21. Best value: 0.402985:  74%|███████▍  | 37/50 [01:37<00:46,  3.61s/it]

[I 2025-12-07 15:30:29,272] Trial 36 finished with value: 0.39097744360902253 and parameters: {'n_estimators': 511, 'learning_rate': 0.19906599461237395, 'num_leaves': 53, 'max_depth': 11, 'min_child_samples': 42, 'subsample': 0.9248501302185671, 'colsample_bytree': 0.712427390186963, 'reg_alpha': 0.022446662284591613, 'reg_lambda': 0.04331622294012121}. Best is trial 21 with value: 0.40298507462686567.

Best trial: 21. Best value: 0.402985:  76%|███████▌  | 38/50 [01:42<00:47,  3.97s/it]

[I 2025-12-07 15:30:34,055] Trial 37 finished with value: 0.3851851851851852 and parameters: {'n_estimators': 688, 'learning_rate': 0.15288510653784174, 'num_leaves': 60, 'max_depth': 9, 'min_child_samples': 11, 'subsample': 0.8686335267152752, 'colsample_bytree': 0.809637009248785, 'reg_alpha': 0.002606340658445679, 'reg_lambda': 0.08476807550391764}. Best is trial 21 with value: 0.40298507462686567.

Best trial: 21. Best value: 0.402985:  78%|███████▊  | 39/50 [01:45<00:43,  3.96s/it]

[I 2025-12-07 15:30:38,007] Trial 38 finished with value: 0.366412213740458 and parameters: {'n_estimators': 762, 'learning_rate': 0.09617417027898893, 'num_leaves': 42, 'max_depth': 11, 'min_child_samples': 56, 'subsample': 0.9743554954663878, 'colsample_bytree': 0.8615973229351463, 'reg_alpha': 0.010167232084981218, 'reg_lambda': 0.22931708399396122}. Best is trial 21 with value: 0.40298507462686567.

Best trial: 21. Best value: 0.402985:  80%|████████  | 40/50 [01:51<00:43,  4.31s/it]

[I 2025-12-07 15:30:43,141] Trial 39 finished with value: 0.39097744360902253 and parameters: {'n_estimators': 766, 'learning_rate': 0.12168098781435505, 'num_leaves': 56, 'max_depth': 10, 'min_child_samples': 36, 'subsample': 0.8463401356400947, 'colsample_bytree': 0.8866704300903809, 'reg_alpha': 0.02725533034992069, 'reg_lambda': 0.7415869108520537}. Best is trial 21 with value: 0.40298507462686567.

Best trial: 21. Best value: 0.402985:  82%|████████▏ | 41/50 [01:54<00:36,  4.03s/it]

[I 2025-12-07 15:30:46,512] Trial 40 finished with value: 0.40298507462686567 and parameters: {'n_estimators': 589, 'learning_rate': 0.18598494630225784, 'num_leaves': 48, 'max_depth': 9, 'min_child_samples': 27, 'subsample': 0.9154547234364698, 'colsample_bytree': 0.999746852364571, 'reg_alpha': 0.005226477253883303, 'reg_lambda': 1.5633847468273148}. Best is trial 21 with value: 0.40298507462686567.

Best trial: 21. Best value: 0.402985:  84%|████████▍ | 42/50 [01:58<00:31,  3.98s/it]

[I 2025-12-07 15:30:50,377] Trial 41 finished with value: 0.40298507462686567 and parameters: {'n_estimators': 544, 'learning_rate': 0.19157256959726038, 'num_leaves': 56, 'max_depth': 12, 'min_child_samples': 33, 'subsample': 0.9369624141726508, 'colsample_bytree': 0.7145577682958063, 'reg_alpha': 0.008773711198420697, 'reg_lambda': 0.04758458834677832}. Best is trial 21 with value: 0.40298507462686567.

Best trial: 21. Best value: 0.402985:  86%|████████▌ | 43/50 [02:02<00:27,  3.91s/it]

[I 2025-12-07 15:30:54,136] Trial 42 finished with value: 0.39097744360902253 and parameters: {'n_estimators': 563, 'learning_rate': 0.1754211853908945, 'num_leaves': 53, 'max_depth': 12, 'min_child_samples': 36, 'subsample': 0.9606313567546438, 'colsample_bytree': 0.7294895244596933, 'reg_alpha': 0.014818942541398268, 'reg_lambda': 0.2370747171318337}. Best is trial 21 with value: 0.40298507462686567.

Best trial: 21. Best value: 0.402985:  88%|████████▊ | 44/50 [02:05<00:22,  3.75s/it]

[I 2025-12-07 15:30:57,490] Trial 43 finished with value: 0.304 and parameters: {'n_estimators': 496, 'learning_rate': 0.05127896142124836, 'num_leaves': 52, 'max_depth': 11, 'min_child_samples': 43, 'subsample': 0.9853209783012552, 'colsample_bytree': 0.7759073296556422, 'reg_alpha': 0.00790425642471329, 'reg_lambda': 0.061552206194700886}. Best is trial 21 with value: 0.40298507462686567.

Best trial: 21. Best value: 0.402985:  90%|█████████ | 45/50 [02:09<00:19,  3.92s/it]

[I 2025-12-07 15:31:01,822] Trial 44 finished with value: 0.39705882352941174 and parameters: {'n_estimators': 581, 'learning_rate': 0.19976676199957125, 'num_leaves': 62, 'max_depth': 10, 'min_child_samples': 22, 'subsample': 0.9552506728799449, 'colsample_bytree': 0.7468918812827856, 'reg_alpha': 0.004093614787679849, 'reg_lambda': 0.013956377741374286}. Best is trial 21 with value: 0.40298507462686567.

Best trial: 21. Best value: 0.402985:  92%|█████████▏| 46/50 [02:14<00:16,  4.06s/it]

[I 2025-12-07 15:31:06,216] Trial 45 finished with value: 0.39097744360902253 and parameters: {'n_estimators': 622, 'learning_rate': 0.18952107169324914, 'num_leaves': 55, 'max_depth': 12, 'min_child_samples': 30, 'subsample': 0.8746868989375238, 'colsample_bytree': 0.6363354344562664, 'reg_alpha': 0.03631480479952131, 'reg_lambda': 0.09432435207048813}. Best is trial 21 with value: 0.40298507462686567.

Best trial: 21. Best value: 0.402985:  94%|█████████▍| 47/50 [02:17<00:11,  3.72s/it]

[I 2025-12-07 15:31:09,136] Trial 46 finished with value: 0.366412213740458 and parameters: {'n_estimators': 531, 'learning_rate': 0.16441273588585373, 'num_leaves': 44, 'max_depth': 11, 'min_child_samples': 53, 'subsample': 0.9136548371670952, 'colsample_bytree': 0.7121208556048132, 'reg_alpha': 0.0018083248634474178, 'reg_lambda': 0.02896118356482475}. Best is trial 21 with value: 0.40298507462686567.

Best trial: 21. Best value: 0.402985:  96%|█████████▌| 48/50 [02:20<00:07,  3.68s/it]

[I 2025-12-07 15:31:12,710] Trial 47 finished with value: 0.40298507462686567 and parameters: {'n_estimators': 471, 'learning_rate': 0.17457107653233447, 'num_leaves': 67, 'max_depth': 9, 'min_child_samples': 16, 'subsample': 0.9411985514088572, 'colsample_bytree': 0.903339796395648, 'reg_alpha': 0.019321609774600988, 'reg_lambda': 0.32351827971996105}. Best is trial 21 with value: 0.40298507462686567.

Best trial: 21. Best value: 0.402985:  98%|█████████▊| 49/50 [02:23<00:03,  3.56s/it]

[I 2025-12-07 15:31:16,007] Trial 48 finished with value: 0.39097744360902253 and parameters: {'n_estimators': 689, 'learning_rate': 0.14193481553721954, 'num_leaves': 50, 'max_depth': 7, 'min_child_samples': 44, 'subsample': 0.8764597227142066, 'colsample_bytree': 0.9515703532551643, 'reg_alpha': 0.009865253308333452, 'reg_lambda': 0.16037288358025215}. Best is trial 21 with value: 0.40298507462686567.

Best trial: 21. Best value: 0.402985: 100%|██████████| 50/50 [02:26<00:00,  2.94s/it]

[I 2025-12-07 15:31:18,966] Trial 49 finished with value: 0.3787878787878788 and parameters: {'n_estimators': 393, 'learning_rate': 0.19040662787831492, 'num_leaves': 64, 'max_depth': 10, 'min_child_samples': 49, 'subsample': 0.8849777652140816, 'colsample_bytree': 0.8581900559105033, 'reg_alpha': 0.0489319922533663, 'reg_lambda': 0.06363034100656144}. Best is trial 21 with value: 0.40298507462686567.

In [71]:
best_params = study.best_params

model_best = LGBMClassifier(
    random_state=42,
    n_jobs=-1,
    **best_params
)

In [72]:
model_best.fit(X_train, y_train)
probs = model_best.predict_proba(X_test)[:, 1]

In [73]:
print(classification_report(y_test, final_preds))

              precision    recall  f1-score   support

           0       0.99      0.98      0.98      7169
           1       0.18      0.30      0.22       123

    accuracy                           0.97      7292
   macro avg       0.58      0.64      0.60      7292
weighted avg       0.97      0.97      0.97      7292

In [74]:
feature_importance = pd.DataFrame({'feature': X.columns,'importance': model_best.feature_importances_}).sort_values('importance', ascending=False)
feature_importance.head(20)

                feature  importance
13                  AGE        9891
15           LOG_INCOME        8663
14           EXPERIENCE        6071
6    NAME_FAMILY_STATUS        1914
4      NAME_INCOME_TYPE        1853
12      CNT_FAM_MEMBERS        1552
5   NAME_EDUCATION_TYPE        1372
3          CNT_CHILDREN         933
7     NAME_HOUSING_TYPE         833
2       FLAG_OWN_REALTY         832
0           CODE_GENDER         822
10           FLAG_PHONE         712
1          FLAG_OWN_CAR         623
9       FLAG_WORK_PHONE         512
11           FLAG_EMAIL         244
8            FLAG_MOBIL           0

# LIGHTGBM + Hyperparameter Tuning + Threshold Tuning

In [75]:
thresholds = np.linspace(0.1, 0.99, 200)
best_f1 = 0
best_t = 0.5

for t in thresholds:
    preds = (probs >= t).astype(int)
    score = f1_score(y_test, preds)
    if score > best_f1:
        best_f1 = score
        best_t = t

In [76]:
best_t

np.float64(0.18944723618090453)

In [77]:
final_preds = (probs >= best_t).astype(int)
print(classification_report(y_test, final_preds))

              precision    recall  f1-score   support

           0       0.99      0.98      0.99      7169
           1       0.29      0.41      0.34       123

    accuracy                           0.97      7292
   macro avg       0.64      0.69      0.66      7292
weighted avg       0.98      0.97      0.98      7292

In [87]:
path_to_model = path_to_repo / 'models'
joblib.dump(model_best, path_to_model / "best_lgbm.pkl")

['/Users/arystankamalov/Documents/GitHub/emlyon_ml_project/models/best_lgbm.pkl']

In [79]:
feature_importance = pd.DataFrame({'feature': X.columns,'importance': model_best.feature_importances_}).sort_values('importance', ascending=False)
feature_importance.head(20)

                feature  importance
13                  AGE        9891
15           LOG_INCOME        8663
14           EXPERIENCE        6071
6    NAME_FAMILY_STATUS        1914
4      NAME_INCOME_TYPE        1853
12      CNT_FAM_MEMBERS        1552
5   NAME_EDUCATION_TYPE        1372
3          CNT_CHILDREN         933
7     NAME_HOUSING_TYPE         833
2       FLAG_OWN_REALTY         832
0           CODE_GENDER         822
10           FLAG_PHONE         712
1          FLAG_OWN_CAR         623
9       FLAG_WORK_PHONE         512
11           FLAG_EMAIL         244
8            FLAG_MOBIL           0